export function encodePcmWav(chunks,rate){const count=chunks.reduce((n,c)=>n+c.length,0),bytes=new ArrayBuffer(44+count*2),v=new DataView(bytes),u=new Uint8Array(bytes),tag=(p,t)=>u.set(new TextEncoder().encode(t),p);tag(0,'RIFF');v.setUint32(4,bytes.byteLength-8,true);tag(8,'WAVE');tag(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,rate,true);v.setUint32(28,rate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);tag(36,'data');v.setUint32(40,count*2,true);let p=44;for(const chunk of chunks)for(const sample of chunk){const s=Math.max(-1,Math.min(1,sample));v.setInt16(p,s<0?s*32768:s*32767,true);p+=2;}return bytes;}
export function createVoiceAdapter({adapter,tokenFor,fetcher=fetch,maxSeconds=30}){
 let generation=0,stream=null,context=null,node=null,source=null,chunks=[],sampleCount=0,timer=null,player=null,playResolve=null,playStarted=false,playContext=null;let exposureQueue=Promise.resolve();const audioCache=new Map(),transcriptionIds=new WeakMap();
 const request=async(path,init,id)=>{const res=await fetcher(path,{...init,credentials:'same-origin',headers:{...init.headers,Authorization:'Bearer '+tokenFor(id),'X-Workflow-Id':init.headers?.['X-Question-Id']||window.playlogueFrontend?.state.session?.current||''}});if(!res.ok){const data=await res.json().catch(()=>({}));throw Object.assign(new Error((data.error?.message||'Audio request failed.')+(data.error?.diagnostic_id?' Reference: '+data.error.diagnostic_id:'')),{code:data.error?.code||'AUDIO_ERROR',diagnostic_id:data.error?.diagnostic_id||null});}return res;};
 const cleanupCapture=()=>{clearTimeout(timer);timer=null;node?.disconnect();source?.disconnect();stream?.getTracks().forEach(t=>t.stop());context?.close().catch(()=>{});node=null;source=null;stream=null;};
 const exposure=(state,{sessionId,questionId},g)=>{const task=exposureQueue.then(async()=>{const s=await adapter.getSession(sessionId);if(s.status!=='active'||s.mode!=='voice'||s.current!==questionId)return;const saved=await adapter.command(sessionId,{type:'exposure',request_id:crypto.randomUUID(),expected_state_version:s.state_version,question_id:questionId,channel:'audio',state,attempt_id:'play-'+questionId});const f=window.playlogueFrontend;if(f?.state.session?.id===sessionId&&saved.state_version>=f.state.session.state_version)f.state.session=saved;});exposureQueue=task.catch(()=>{});return task;};
 const stopPlayback=()=>{const old=generation;if(player&&playStarted&&playContext)exposure('partial',playContext,old).catch(()=>{});generation++;player?.pause();if(player){player.onended=null;player.onerror=null;player.onplaying=null;}player=null;playStarted=false;playResolve?.();playResolve=null;};
 return {
  async record({maxSeconds:requested=90,maxBytes=8388608,onAutoStop}){stopPlayback();cleanupCapture();const g=generation;chunks=[];sampleCount=0;const granted=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true},video:false});if(g!==generation){granted.getTracks().forEach(t=>t.stop());return;}stream=granted;try{context=new AudioContext();await context.audioWorklet.addModule('/client/pcm-worklet.js');if(g!==generation){cleanupCapture();return;}source=context.createMediaStreamSource(stream);node=new AudioWorkletNode(context,'playlogue-pcm-recorder');const cap=Math.floor(Math.min(requested,maxSeconds)*context.sampleRate),byteCap=Math.floor((maxBytes-44)/2);let auto=false;const stop=()=>{if(!auto&&g===generation){auto=true;node?.disconnect();onAutoStop?.();}};node.port.onmessage=e=>{if(g!==generation||auto)return;const data=new Float32Array(e.data),left=Math.min(cap,byteCap)-sampleCount;if(left>0){const c=data.slice(0,left);chunks.push(c);sampleCount+=c.length;}if(sampleCount>=Math.min(cap,byteCap))stop();};source.connect(node);node.connect(context.destination);timer=setTimeout(stop,Math.min(requested,maxSeconds)*1000);}catch(error){cleanupCapture();context=null;throw error;}},
  async stop(){if(!context)throw Object.assign(new Error('No recording is active.'),{code:'NO_RECORDING'});const rate=context.sampleRate,data=encodePcmWav(chunks,rate);cleanupCapture();context=null;chunks=[];sampleCount=0;return new Blob([data],{type:'audio/wav'});},
  async transcribe(recording,{sessionId,questionId}){if(!(recording instanceof Blob)||recording.size>8388608)throw new Error('Unsupported recording.');let id=transcriptionIds.get(recording);if(!id){id=crypto.randomUUID();transcriptionIds.set(recording,id);}const res=await request('/api/sessions/'+sessionId+'/stt',{method:'POST',headers:{'Content-Type':'audio/wav','X-Question-Id':questionId,'X-Request-Id':id},body:recording},sessionId);return res.json();},
  async playQuestion(_clientText,ctx){stopPlayback();const g=generation,key=ctx.sessionId+':'+ctx.questionId;let blob=audioCache.get(key);if(!blob){const res=await request('/api/sessions/'+ctx.sessionId+'/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question_id:ctx.questionId,request_id:crypto.randomUUID()})},ctx.sessionId);blob=await res.blob();if(g!==generation)return;audioCache.set(key,blob);while(audioCache.size>20||[...audioCache.values()].reduce((n,b)=>n+b.size,0)>33554432)audioCache.delete(audioCache.keys().next().value);}if(g!==generation)return;const url=URL.createObjectURL(blob);player=new Audio(url);playContext=ctx;await new Promise((resolve,reject)=>{playResolve=resolve;player.onplaying=()=>{if(g!==generation)return;playStarted=true;exposure('start',ctx,g).catch(()=>{});ctx.onPlaybackStart?.();};player.onended=()=>{if(g!==generation)return;exposure('full',ctx,g).then(resolve,reject).finally(()=>URL.revokeObjectURL(url));};player.onerror=()=>{exposure('failed',ctx,g).catch(()=>{});URL.revokeObjectURL(url);reject(new Error('Audio playback failed.'));};player.play().catch(reject);});URL.revokeObjectURL(url);},
  stopPlayback,
  cancel(){stopPlayback();cleanupCapture();context=null;chunks=[];sampleCount=0;audioCache.clear();}
 };
}
