import {test}from'node:test';import assert from'node:assert/strict';import {initialBudget,reserveCall,settleCall}from'../shared/budget.mjs';
const now=Date.parse('2026-10-04T03:00:00Z'),req=(task_id='task',extra={})=>({task_id,operation:'decision',session_id:'s',ceiling_micro_usd:1000000,price_version:'synthetic-test-price',...extra}),enabled=()=>({...initialBudget(),live_enabled:true});
test('USD20 cap recorded but default live disabled and missing price ceiling denied',()=>{assert.equal(initialBudget().approved_cap_micro_usd,20000000);assert.throws(()=>reserveCall(initialBudget(),req(),now),/LIVE_DISABLED/);assert.throws(()=>reserveCall(enabled(),req('x',{price_version:null}),now),/CEILING_REQUIRED/);});
test('concurrent holds and unknown cost cannot exceed approved cap',()=>{let c=reserveCall(enabled(),req('a',{ceiling_micro_usd:15000000}),now);c=settleCall(c,'a',null);assert.throws(()=>reserveCall(c,req('b',{ceiling_micro_usd:6000000}),now+70000),/COST_CAP/);c=reserveCall(c,req('b',{ceiling_micro_usd:5000000}),now+70000);assert.equal(c.reservations.length,2);});
test('two concurrent leases only; expiration restores slot without refunding unknown spending',()=>{let c=reserveCall(enabled(),req('a'),now);c=reserveCall(c,req('b'),now);assert.throws(()=>reserveCall(c,req('c'),now),/CONCURRENCY_LIMIT/);c=reserveCall(c,req('c'),now+61000);assert.equal(c.reservations.length,3);});
test('same reservation dedupes and mutated task fails',()=>{const c=reserveCall(enabled(),req(),now);assert.deepEqual(reserveCall(c,req(),now),c);assert.throws(()=>reserveCall(c,req('task',{ceiling_micro_usd:2000000}),now),/RESERVATION_MISMATCH/);});
test('known settlement releases hold once; unexpected actual overrun shuts live off',()=>{let c=reserveCall(enabled(),req(),now);c=settleCall(c,'task',500000,{confirmed_finished:true});assert.equal(c.known_spend_micro_usd,500000);assert.deepEqual(settleCall(c,'task',500000),c);c=reserveCall(c,req('over'),now);c=settleCall(c,'over',2000000);assert.equal(c.live_enabled,false);assert.equal(c.overrun_detected,true);});
test('failed and uncertain attempts count toward session limit; STT conservative duration enforced',()=>{let c=enabled();for(let i=0;i<12;i++){c=reserveCall(c,req('task'+i,{ceiling_micro_usd:1}),now);c=settleCall(c,'task'+i,null,{confirmed_finished:true});}assert.throws(()=>reserveCall(c,req('task12'),now),/CALL_LIMIT/);c=enabled();for(let i=0;i<6;i++){c=reserveCall(c,req('audio'+i,{operation:'stt',ceiling_micro_usd:1}),now);c=settleCall(c,'audio'+i,null,{confirmed_finished:true});}assert.throws(()=>reserveCall(c,req('audio6',{operation:'stt'}),now),/AUDIO_LIMIT/);});
test('public cutoff denies new reservations',()=>{assert.throws(()=>reserveCall(enabled(),req(),Date.parse('2026-10-04T16:00:00Z')),/CALL_CUTOFF/);});
