import test from'node:test';import assert from'node:assert/strict';
import {api,Repository,sha256,analysisInput,validateAnalysis}from'../work/test-api.mjs';
import {localD1}from'./sqlite-d1.mjs';import {validateCustomStudy,customGuide}from'../shared/custom-study.mjs';
import {createSession,transition,draft,publish}from'../shared/session.mjs';
import {encodePcmWav}from'../client/voice-adapter.js';
const origin='http://localhost:4175',token='J'.repeat(43),consent={adult_confirmed:true,research_agreed:true,cloud_agreed:true};
const input=(n=4)=>({title:'Synthetic custom study',goal:'Understand fictional navigation decisions.',game:'Synthetic game',game_build:'test-1',target_players:'Synthetic nonpersonal test fixtures',questions:Array.from({length:n},(_,i)=>({text:`Synthetic question ${i+1}?`,allow_followups:i===n-1&&n<9,followup_limit:i===n-1&&n<9?Math.min(2,9-n):0}))});
const context=()=>{const DB=localD1(),repo=new Repository(DB);return {DB,repo,env:{DB,APP_ORIGIN:origin,AUTH_MODE:'sites-dispatch',SITE_ACCESS_MODE:'owner-private',RESEARCHER_USER_ID:'owner',CUSTOM_RESEARCH_ENABLED:'true'}};};
async function req(c,path,{method='GET',data,owner=true,requestOrigin=origin}={}){const r=await api(new Request(origin+path,{method,headers:{Authorization:'Bearer '+token,...owner?{'oai-authenticated-user-id':'owner'}:{},...method!=='GET'?{Origin:requestOrigin,'Content-Type':'application/json'}:{}},...data?{body:JSON.stringify(data)}:{}}),c.env);return {status:r.status,data:await r.json()};}
const save=(c,data=input(),id='custom-create')=>req(c,'/api/research/custom-studies',{method:'POST',data:{request_id:id,confirmed:true,draft:data}});
function command(s,g,c){return transition(s,g,{request_id:crypto.randomUUID(),expected_version:s.state_version,...c}).session;}

test('shared validation: all text boundaries, exact keys, booleans, budgets and question ceiling',()=>{
 for(const [field,max]of Object.entries({title:120,goal:1000,game:120,game_build:120,target_players:500})){assert.equal(validateCustomStudy({...input(),[field]:'x'.repeat(max)})[field].length,max);for(const v of ['', ' ', null, 'x'.repeat(max+1)])assert.throws(()=>validateCustomStudy({...input(),[field]:v}),/INVALID_CUSTOM_STUDY/);}
 const q=input(1);q.questions[0].text='x'.repeat(400);assert.equal(validateCustomStudy(q).questions[0].text.length,400);q.questions[0].text+='x';assert.throws(()=>validateCustomStudy(q));
 for(const bad of [{...input(),unknown:true},{...input(),questions:[]},{...input(),questions:input(9).questions.concat(input(1).questions)},{...input(),questions:input(4).questions.map(q=>({...q,allow_followups:true,followup_limit:2}))},{...input(),questions:[{text:'x',allow_followups:false,followup_limit:1}]},{...input(),questions:[{text:'x',allow_followups:'true',followup_limit:2}]},{...input(),questions:[{text:'x',allow_followups:true,followup_limit:0}]},{...input(),questions:[{text:'x',allow_followups:true,followup_limit:3}]}])assert.throws(()=>validateCustomStudy(bad));
 assert.equal(validateCustomStudy(input(9)).questions.length,9);
 const large=input(9);for(const [k,max]of Object.entries({title:120,goal:1000,game:120,game_build:120,target_players:500}))large[k]='界'.repeat(max);large.questions.forEach(q=>q.text='界'.repeat(400));assert.throws(()=>validateCustomStudy(large),/INVALID_CUSTOM_STUDY/);
});
test('legacy custom multi-topic full budget charges only committed probes and never exceeds nine',()=>{const d=input(3);d.questions.forEach(q=>{q.allow_followups=true;q.followup_limit=2;});const g={...customGuide(d,'multi'),routing_policy:'fixed-first-v1'};let s=createSession(g,consent);while(s.status==='active'){if(s.step==='awaiting_answer')s=command(s,g,{type:'answer',question_id:s.current,response_status:'skipped',input_mode:'text'});else s=command(s,g,{type:'decision',task_id:s.task.id,input_content_revision:s.content_revision,action:'probe',theme_id:s.task.theme_id,question_text:'Synthetic probe '+s.questions.length});}assert.equal(s.questions.length,9);assert.deepEqual(s.used,{T1:2,T2:2,T3:2});});
test('legacy 1–9 fixed questions remain ordered and fixed cannot probe, with text/voice parity and max nine',()=>{
 for(let n=1;n<=9;n++)for(const mode of ['text','voice']){const g={...customGuide(input(n),'synthetic-study'),routing_policy:'fixed-first-v1'};let s=createSession(g,consent,{origin:'demo_fixture',mode});const snap=JSON.stringify(g);
 for(let i=0;i<n;i++){assert.equal(s.questions.at(-1).fixed_question_id,'F'+(i+1));s=command(s,g,{type:'answer',question_id:s.current,response_status:'valid',final_text:'Synthetic response',input_mode:mode});assert.throws(()=>command(s,g,{type:'decision',task_id:s.task.id,input_content_revision:s.content_revision,action:'probe',theme_id:s.task.theme_id,question_text:'Premature?'}),/FIXED_BLOCK/);s=command(s,g,{type:'decision',task_id:s.task.id,input_content_revision:s.content_revision,action:'advance'});}
 while(s.status==='active'){const task=s.task;assert.equal(task.theme_id,'T'+n);s=command(s,g,{type:'decision',task_id:task.id,input_content_revision:s.content_revision,action:'probe',theme_id:task.theme_id,question_text:'Synthetic follow-up '+s.questions.length});s=command(s,g,{type:'answer',question_id:s.current,response_status:'skipped',final_text:'',input_mode:mode});}
 assert.ok(s.questions.length<=9);assert.equal(s.questions.length,n+Math.min(2,9-n));assert.equal(JSON.stringify(g),snap);}
});
test('custom refusal and zero budget cannot produce probes; legacy preset stays exact',()=>{const g=customGuide(input(),'s');let s=createSession(g,consent);for(let i=0;i<4;i++)s=command(s,g,{type:'answer',question_id:s.current,response_status:'refused',input_mode:'text'});assert.equal(s.status,'ended');assert.equal(s.questions.length,4);assert.deepEqual(publish(draft).themes,draft.themes);});
test('API defaults off, owner/Origin/confirmation/unknown fields and malformed drafts deny without calls',async()=>{const c=context();try{const pre=await c.repo.initialize('owner');c.env.CUSTOM_RESEARCH_ENABLED=undefined;assert.equal((await save(c)).status,404);c.env.CUSTOM_RESEARCH_ENABLED='true';assert.equal((await req(c,'/api/research/custom-studies',{owner:false})).status,403);assert.equal((await req(c,'/api/research/custom-studies',{method:'POST',requestOrigin:'https://evil.example',data:{}})).status,403);for(const data of [{request_id:'x',confirmed:false,draft:input()},{request_id:'x',confirmed:true,draft:input(),extra:true}])assert.equal((await req(c,'/api/research/custom-studies',{method:'POST',data})).status,422);assert.equal((await save(c,{...input(),goal:'x'.repeat(1001)})).status,422);assert.equal((await c.repo.guide()).id,pre.id);assert.equal(await c.repo.providerAttemptCount(),0);}finally{c.DB.close();}});
test('atomic independent save, concurrent retries, payload mismatch, immutable preset and listing',async()=>{const c=context();try{const preset=await c.repo.initialize('owner'),s=await c.repo.create(preset,consent,'demo_fixture','text',await sha256(token),'legacy','legacy');const before=JSON.stringify((await c.repo.get(s.id)).session);const [a,b]=await Promise.all([save(c),save(c)]);assert.ok([200,201].includes(a.status));assert.equal(a.data.guide.id,b.data.guide.id);assert.equal((await save(c,{...input(),game:'different'})).status,409);assert.equal(c.DB.sqlite.prepare("SELECT COUNT(*) n FROM studies WHERE id LIKE 'custom-%'").get().n,1);assert.equal((await c.repo.guide()).id,preset.id);assert.equal(JSON.stringify((await c.repo.get(s.id)).session),before);assert.equal((await req(c,'/api/public/study')).data.guide.id,'builtin-detonation-gameplay-feedback-v3');assert.equal((await req(c,'/api/research/custom-studies')).data.guides[0].id,a.data.guide.id);const created=await c.repo.create(a.data.guide,consent,'demo_fixture','voice',await sha256(token),'custom-session','p');assert.equal(c.DB.sqlite.prepare('SELECT study_id FROM sessions WHERE id=?').get(created.id).study_id,a.data.study_id);assert.equal(await c.repo.providerAttemptCount(),0);}finally{c.DB.close();}});
test('transaction failure rolls back study and retry recovers',async()=>{const c=context();try{const batch=c.DB.batch;c.DB.batch=statements=>batch([statements[0],{_syncRun(){throw new Error('synthetic crash');}}]);assert.equal((await save(c)).status,503);assert.equal(c.DB.sqlite.prepare('SELECT COUNT(*) n FROM studies').get().n,0);c.DB.batch=batch;assert.equal((await save(c)).status,201);}finally{c.DB.close();}});
test('disabled after save denies selected guide/new sessions but capability recovery/end/delete survive',async()=>{const c=context();try{const {guide:g}= (await save(c)).data;const s=await c.repo.create(g,consent,'demo_fixture','voice',await sha256(token),'custom-s','p');c.env.CUSTOM_RESEARCH_ENABLED='false';assert.equal((await req(c,'/api/public/study?guide_id='+g.id)).status,404);assert.equal((await req(c,'/api/research/fixtures',{method:'POST',data:{guide_id:g.id,request_id:'disabled',consent,mode:'text'}})).status,404);const recovered=await req(c,'/api/sessions/'+s.id,{owner:false});assert.equal(recovered.data.guide.id,g.id);assert.equal(recovered.data.session.questions[0].actual_text,g.themes[0].text);const end=await req(c,'/api/sessions/'+s.id+'/control',{method:'POST',owner:false,data:{action:'end',request_id:'end',expected_state_version:0}});assert.equal(end.status,200);assert.equal((await req(c,'/api/sessions/'+s.id,{method:'DELETE',owner:false,data:{request_id:'delete',expected_state_version:1}})).status,200);assert.equal((await req(c,'/api/sessions/'+s.id,{owner:false})).status,410);}finally{c.DB.close();}});
test('T4 evidence IDs and denominators survive validated analysis; invented topic/span and mixed guide denied',async()=>{const c=context();try{const {guide:g}= (await save(c)).data;let s=await c.repo.create(g,consent,'demo_fixture','text',await sha256(token),'analysis-s','p');for(let i=0;i<4;i++)s=(await c.repo.mutate(s,g,{type:'answer',request_id:'skip-'+i,expected_version:s.state_version,question_id:s.current,response_status:i===3?'valid':'skipped',final_text:i===3?'Synthetic last question evidence.':'',input_mode:'text'})).session;const span=JSON.parse(analysisInput([s])).sessions[0].answers[0].available_span;const f={id:'synthetic-finding',claim:'Tentative synthetic finding',supporting_spans:[span],counter_spans:[],unknowns:['Test only'],theme_ids:['T4']};assert.equal(validateAnalysis({findings:[f]},[s]).findings[0].theme_ids[0],'T4');assert.throws(()=>validateAnalysis({findings:[{...f,theme_ids:['T9']}]},[s]));assert.throws(()=>validateAnalysis({findings:[{...f,supporting_spans:[{...span,question_id:'wrong'}]}]},[s]));const run=await c.repo.snapshot([s],'owner');const result=await c.repo.commitCandidates(run.id,{findings:[f]},'test_fixture');assert.ok(result.denominators.T4);assert.deepEqual(Object.keys(result.denominators),['T1','T2','T3','T4']);const g2=(await save(c,input(),'second')).data.guide;const s2=await c.repo.create(g2,consent,'demo_fixture','text',await sha256(token),'s2','p');assert.equal((await req(c,'/api/research/analysis',{method:'POST',data:{request_id:'mixed',session_ids:[s.id,s2.id],filter:{guide_id:g.id,origin:'demo_fixture',mode_group:'text_only',mode_basis:'eligible'}}})).status,422);}finally{c.DB.close();}});
test('custom text decision uses saved context and dynamic T4 schema through mocked bounded transport',async()=>{const c=context();let calls=0;try{const g=(await save(c)).data.guide;await c.repo.updateBudget(b=>({...b,live_enabled:true,revision:b.revision+1}));c.env.LOCAL_ENGINEERING_TEXT=true;c.env.LOCAL_OPENAI_API_KEY='offline-fixture';c.env.LOCAL_PROVIDER_FETCH=async(_url,options)=>{calls++;const payload=JSON.parse(options.body);assert.ok(JSON.stringify(payload).includes('T4'));assert.ok(JSON.stringify(payload).includes(g.goal));return Response.json({status:'completed',usage:{input_tokens:100,output_tokens:50},output:[{content:[{type:'output_text',text:JSON.stringify({action:'probe',theme_id:'T4',question_text:'Synthetic saved-context probe?',reason:'Synthetic test'})}]}]});};let s=await c.repo.create(g,consent,'demo_live','text',await sha256(token),'transport','p');for(let i=0;i<4;i++)s=(await c.repo.mutate(s,g,{type:'answer',request_id:'skip-'+i,expected_version:s.state_version,question_id:s.current,response_status:i===3?'valid':'skipped',final_text:i===3?'Synthetic vague answer':'',input_mode:'text'})).session;const result=await req(c,'/api/sessions/'+s.id+'/decision',{method:'POST',owner:false,data:{task_id:s.task.id}});assert.equal(result.status,200);assert.equal(result.data.session.questions.at(-1).theme_id,'T4');assert.equal(calls,1);assert.equal((await c.repo.budget()).reservations.length,1);}finally{c.DB.close();}});
test('custom TTS uses the stored fixed text and confirmed voice answer shares question ID, no real provider',async()=>{const c=context();let calls=0;try{const g=(await save(c)).data.guide;await c.repo.updateBudget(b=>({...b,live_enabled:true,revision:b.revision+1}));c.env.LOCAL_ENGINEERING_SPEECH=true;c.env.LOCAL_OPENAI_API_KEY='offline-fixture';c.env.LOCAL_PROVIDER_FETCH=async(_url,options)=>{calls++;assert.equal(JSON.parse(options.body).input,g.themes[0].text);const bytes=new Uint8Array(20*96);for(let i=0;i<20;i++)bytes.set([255,243,68,0],i*96);return new Response(bytes,{headers:{'Content-Type':'audio/mpeg'}});};const s=await c.repo.create(g,consent,'demo_live','voice',await sha256(token),'voice','p');const r=await api(new Request(origin+'/api/sessions/'+s.id+'/tts',{method:'POST',headers:{Origin:origin,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({question_id:s.current,request_id:'tts',input:'Ignored malicious text'})}),c.env);assert.equal(r.status,200);const submitted=await req(c,'/api/sessions/'+s.id+'/answers',{method:'POST',owner:false,data:{request_id:'voice-answer',expected_state_version:0,question_id:s.current,response_status:'valid',input_mode:'voice',final_text:'Synthetic confirmed transcript.',edited_transcript:true}});assert.equal(submitted.status,200);assert.equal(submitted.data.session.answers[0].question_id,s.current);assert.equal(submitted.data.session.answers[0].input_mode,'voice');assert.equal(calls,1);}finally{c.DB.close();}});
test('custom STT remains a draft until confirmation; saved source ID follows backend question',async()=>{const c=context();try{const g=(await save(c)).data.guide;await c.repo.updateBudget(b=>({...b,live_enabled:true,revision:b.revision+1}));c.env.LOCAL_ENGINEERING_SPEECH=true;c.env.LOCAL_OPENAI_API_KEY='offline-fixture';c.env.LOCAL_PROVIDER_FETCH=async()=>Response.json({text:'Synthetic draft transcript.'});const s=await c.repo.create(g,consent,'demo_live','voice',await sha256(token),'stt-s','p');const r=await api(new Request(origin+'/api/sessions/'+s.id+'/stt',{method:'POST',headers:{Origin:origin,Authorization:'Bearer '+token,'Content-Type':'audio/wav','X-Question-Id':s.current,'X-Request-Id':'stt-r'},body:encodePcmWav([new Float32Array(2400)],24000)}),c.env);assert.equal(r.status,200);const transcript=await r.json();assert.equal((await c.repo.get(s.id)).session.answers.length,0);const confirmed=await req(c,'/api/sessions/'+s.id+'/answers',{method:'POST',owner:false,data:{request_id:'confirm-stt',expected_state_version:0,question_id:s.current,response_status:'valid',input_mode:'voice',final_text:transcript.text,transcript_source_task_id:transcript.provider_task_id}});assert.equal(confirmed.status,200);assert.equal(confirmed.data.session.answers[0].question_id,s.current);assert.equal(confirmed.data.session.answers[0].transcript_source_task_id,transcript.provider_task_id);}finally{c.DB.close();}});
