import test from 'node:test';import assert from 'node:assert/strict';
import {api,Repository,sha256}from'../work/test-api.mjs';import {localD1}from'./sqlite-d1.mjs';
import {createHttpAdapter}from'../client/adapter.js';import {createCapabilityStore}from'../client/capabilities.js';
import {initialBudget,reserveCall,settleCall}from'../shared/budget.mjs';
const consent={adult_confirmed:true,research_agreed:true,cloud_agreed:true},origin='http://localhost:4175',token='A'.repeat(43);
function harness(){const DB=localD1(),env={DB,APP_ORIGIN:origin,AUTH_MODE:'sites-dispatch',SITE_ACCESS_MODE:'owner-private',RESEARCHER_USER_ID:'test-owner'},repo=new Repository(DB);const fetcher=(path,init={})=>{const headers=new Headers(init.headers);headers.set('Origin',origin);headers.set('oai-authenticated-user-id','test-owner');return api(new Request(origin+path,{...init,headers}),env);};return {DB,env,repo,adapter:createHttpAdapter({fetcher,tokenFor:id=>id==='s-placeholder'?null:id?token:null})};}
test('real SQLite -> API -> HTTP adapter restores current mode, date, guide and visible exposure CAS',async()=>{const h=harness();try{const g=await h.repo.initialize('test-owner'),s=await h.repo.create(g,consent,'demo_fixture','voice',await sha256(token),'create','payload');const restored=await h.adapter.getSession(s.id);assert.equal(restored.mode,'voice');assert.equal(restored.created_at,s.created_at);assert.equal(restored.guide_snapshot.id,g.id);const switched=await h.adapter.command(s.id,{type:'switch_mode',request_id:'switch',expected_state_version:0,mode:'text'});const presented=await h.adapter.command(s.id,{type:'exposure',request_id:'presented',expected_state_version:switched.state_version,question_id:s.current,channel:'text',state:'full',attempt_id:'presentation'});const answered=await h.adapter.command(s.id,{type:'answer',request_id:'answer',expected_state_version:presented.state_version,question_id:s.current,response_status:'valid',final_text:'Offline test response.',input_mode:'text'});assert.equal(answered.mode,'text');assert.equal(answered.initial_mode,'voice');assert.equal(answered.exposures[0].state,'full');assert.equal(answered.answers.length,1);}finally{h.DB.close();}});
test('D1 claim grants one issuer and rejects stale, withdrawn or unconsented sources',async()=>{const h=harness();try{const g=await h.repo.initialize('test-owner'),s=await h.repo.create(g,consent,'demo_fixture','text',await sha256(token),'create','payload');const t={task_id:'business',session_id:s.id,content_revision:s.content_revision,operation:'decision'};const claims=await Promise.all([h.repo.claimAttempt('a1',t,'gpt-6.1-sol'),h.repo.claimAttempt('a2',t,'gpt-6.1-sol')]);assert.equal(claims.filter(Boolean).length,1);assert.equal(await h.repo.claimAttempt('a3',{...t,task_id:'stale',content_revision:4},'gpt-6.1-sol'),false);await h.repo.mutate(s,g,{type:'withdraw',request_id:'withdraw',expected_version:0});assert.equal(await h.repo.claimAttempt('a4',{...t,task_id:'withdrawn',content_revision:1},'gpt-6.1-sol'),false);}finally{h.DB.close();}});
test('private capability remains sessionStorage-only; recovery uses fragment and drops query',()=>{const map=new Map(),storage={getItem:k=>map.get(k),setItem:(k,v)=>map.set(k,v)};const store=createCapabilityStore(storage),cap=store.generate();assert.equal(cap.length,43);store.set('session-id',cap);const url=new URL(store.recoveryLink('session-id','https://private.example/?tracking=1#interview'));assert.equal(url.search,'?adapter=api');assert.equal(store.importFragment(url.hash),'session-id');const restored=createCapabilityStore(storage);assert.equal(restored.get('session-id'),cap);assert.equal(restored.importFragment('#session=bad&cap=not-a-capability'),null);restored.remove('session-id');assert.equal(restored.get('session-id'),null);});
test('engineering accounting keeps upper-bound charge separate from confirmed actual billing',()=>{const b=initialBudget();b.live_enabled=true;const reserved=reserveCall(b,{task_id:'attempt',session_id:'session',operation:'decision',ceiling_micro_usd:100480,price_version:'offline'},Date.parse('2026-10-04T01:00:00Z'));const next=settleCall(reserved,'attempt',100480,{confirmed_finished:true,cost_basis:'upper_bound'});assert.equal(next.reservations[0].actual_micro_usd,undefined);assert.equal(next.reservations[0].cost_basis,'upper_bound');assert.equal(next.reservations[0].accounted_micro_usd,100480);});
