import test from 'node:test';import assert from 'node:assert/strict';
import {BoundedTransport,validatePcmWav}from'../work/test-api.mjs';
const task={task_id:'business-1',session_id:'s1',operation:'decision',content_revision:1};
const schema={type:'object',properties:{action:{type:'string'}},required:['action'],additionalProperties:false};
const ready={enabled:true,identity_verified:true,cloud_consent_verified:true,api_key:'offline-fixture-key',price_version:'offline-price-fixture',inputTokenBound:async()=>32000,stt_price_ceiling_verified:false};
function ledger(){return {calls:[],claims:new Set(),paused:false,async reserve(r){this.calls.push(['reserve',r]);},async claimAttempt(id,t){if(this.claims.has(t.task_id))return false;this.claims.add(t.task_id);return true;},async settle(...args){this.calls.push(['settle',...args]);},async finishAttempt(...args){this.calls.push(['finish',...args]);},async pauseLive(){this.paused=true;}};}
function wav(seconds=1){const samples=16000*seconds,b=new ArrayBuffer(44+samples*2),v=new DataView(b),u=new Uint8Array(b);const tag=(p,t)=>u.set(new TextEncoder().encode(t),p);tag(0,'RIFF');v.setUint32(4,b.byteLength-8,true);tag(8,'WAVE');tag(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,16000,true);v.setUint32(28,32000,true);v.setUint16(32,2,true);v.setUint16(34,16,true);tag(36,'data');v.setUint32(40,samples*2,true);return b;}
test('disabled, identity, consent, missing and excessive token bounds make zero sends',async()=>{for(const patch of [{enabled:false},{identity_verified:false},{cloud_consent_verified:false},{inputTokenBound:undefined},{inputTokenBound:async()=>32001}]){let sends=0;const l=ledger(),p=new BoundedTransport(l,{...ready,...patch},async()=>{sends++;});await assert.rejects(p.text(task,'input',schema,x=>x));assert.equal(sends,0);assert.equal(l.calls.length,0);}});
test('strict fixed-model request reserves before send; same business task cannot issue twice',async()=>{const l=ledger();let sends=0;const p=new BoundedTransport(l,ready,async(url,init)=>{sends++;assert.equal(l.calls[0][0],'reserve');const b=JSON.parse(init.body);assert.equal(b.model,'gpt-6.1-sol');assert.equal(b.store,false);assert.equal(b.reasoning.effort,'low');assert.equal(b.reasoning.mode,'standard');assert.equal(b.service_tier,'default');assert.equal(b.max_output_tokens,2048);assert.equal(b.text.format.strict,true);assert.deepEqual(b.tools,[]);return Response.json({status:'completed',usage:{input_tokens:4,output_tokens:10},output:[{content:[{type:'output_text',text:'{"action":"continue"}'}]}]});});assert.deepEqual(await p.text(task,'input',schema,x=>x),{action:'continue'});assert.equal(l.calls[0][1].ceiling_micro_usd,100480);await assert.rejects(p.text(task,'input',schema,x=>x),e=>e.code==='ATTEMPT_ALREADY_CLAIMED');assert.equal(sends,1);});
test('timeout holds reservation and stops future live budget; no retry',async()=>{const l=ledger();let sends=0;const p=new BoundedTransport(l,ready,async()=>{sends++;throw new Error('network timeout');});await assert.rejects(p.text(task,'input',schema,x=>x),e=>e.code==='PROVIDER_UNAVAILABLE');assert.equal(sends,1);assert.equal(l.paused,true);assert.deepEqual(l.calls.find(x=>x[0]==='settle').slice(2),[null,{confirmed_finished:false}]);});
test('refusal and incomplete text never become business results',async()=>{for(const body of [{status:'incomplete',output:[]},{status:'completed',output:[{content:[{type:'refusal'}]}]},{status:'completed',output:[{content:[{type:'output_text',text:'not-json'}]}]}]){const p=new BoundedTransport(ledger(),ready,async()=>Response.json(body));let validated=false;await assert.rejects(p.text(task,'input',schema,x=>{validated=true;return x;}));assert.equal(validated,false);}});
test('WAV proves actual samples and rejects false metadata, excess duration and non-WAV',()=>{assert.equal(validatePcmWav(wav(90)).seconds,90);assert.throws(()=>validatePcmWav(wav(91)),e=>e.code==='AUDIO_LIMIT');const b=wav();new DataView(b).setUint32(28,1,true);assert.throws(()=>validatePcmWav(b));assert.throws(()=>validatePcmWav(new ArrayBuffer(44)));});
test('STT billing gate and TTS output gate remain independent, no network',async()=>{let sends=0;const p=new BoundedTransport(ledger(),ready,async()=>{sends++;});await assert.rejects(p.stt({...task,operation:'stt'},wav()),e=>e.code==='STT_BILLING_BOUND_REQUIRED');await assert.rejects(p.tts(),e=>e.code==='TTS_PRICE_OUTPUT_BOUND_REQUIRED');assert.equal(sends,0);});
test('validated WAV STT reserves server duration, exact model and bounded transcript',async()=>{const l=ledger();const p=new BoundedTransport(l,{...ready,stt_price_ceiling_verified:true},async(url,init)=>{assert.equal(url,'https://api.openai.com/v1/audio/transcriptions');assert.equal(init.body.get('model'),'gpt-transcribe');assert.equal(init.body.get('file').type,'audio/wav');return Response.json({text:'Example transcript'});});assert.equal(await p.stt({...task,operation:'stt'},wav(2)),'Example transcript');assert.equal(l.calls[0][1].audio_seconds,2);assert.equal(l.calls[0][1].ceiling_micro_usd,9000);});

test('HTTP failure persists safe status/code/param/request ID without raw body, key or provider message',async()=>{const l=ledger(),p=new BoundedTransport(l,ready,async()=>Response.json({error:{code:'invalid_parameter',type:'invalid_request_error',param:'reasoning.mode',message:'RAW_PRIVATE_MESSAGE offline-fixture-key',raw:'PRIVATE_TRANSCRIPT'}},{status:400,headers:{'x-request-id':'req_offline123'}}));await assert.rejects(p.text(task,'PRIVATE_INPUT',schema,x=>x),e=>e.code==='PROVIDER_HTTP_ERROR'&&!!e.provider_call_id);const record=l.calls.find(x=>x[0]==='finish')[3];assert.equal(record.upstream_http_status,400);assert.equal(record.provider_error_param,'reasoning.mode');assert.equal(record.upstream_request_id,'req_offline123');assert.equal(record.local_error_code,'PROVIDER_HTTP_ERROR');assert.doesNotMatch(JSON.stringify(record),/RAW_PRIVATE_MESSAGE|PRIVATE_TRANSCRIPT|offline-fixture-key|PRIVATE_INPUT/);});
test('fetch exception persists exception category/cause and pauses without sensitive message',async()=>{const l=ledger(),p=new BoundedTransport(l,ready,async()=>{throw Object.assign(new TypeError('PRIVATE_NETWORK_MESSAGE'),{cause:{code:'ENOTFOUND'}});});await assert.rejects(p.text(task,'input',schema,x=>x),e=>e.code==='PROVIDER_UNAVAILABLE');const record=l.calls.find(x=>x[0]==='finish')[3];assert.equal(record.transport_error_name,'TypeError');assert.equal(record.transport_cause_code,'ENOTFOUND');assert.doesNotMatch(JSON.stringify(record),/PRIVATE_NETWORK_MESSAGE/);assert.equal(l.paused,true);});

test('default fetch preserves Worker-like global receiver; supplied callable gets no transport receiver',async()=>{const original=globalThis.fetch;try{globalThis.fetch=function(){if(this!==globalThis)throw new TypeError('Illegal invocation');return Response.json({status:'completed',usage:{input_tokens:4,output_tokens:10},output:[{content:[{type:'output_text',text:'{"action":"continue"}'}]}]});};const legacy={send:globalThis.fetch};assert.throws(()=>legacy.send(),/Illegal invocation/);const p=new BoundedTransport(ledger(),ready);assert.deepEqual(await p.text(task,'input',schema,x=>x),{action:'continue'});let observed;const custom=new BoundedTransport(ledger(),ready,function(){observed=this;return Response.json({status:'completed',usage:{input_tokens:4,output_tokens:10},output:[{content:[{type:'output_text',text:'{"action":"continue"}'}]}]});});await custom.text(task,'input',schema,x=>x);assert.equal(observed,undefined);}finally{globalThis.fetch=original;}});
