import{isPublicDemoSession}from'./public-demo.ts';
import {buildVersion}from'./build-info.ts';
import {gameplayExample}from'../shared/detonation-case.mjs';
import {builtinDefaultGuideId,isBuiltinGuide,isBuiltinGuideId}from'../shared/default-guide.mjs';
import {Repository,ApiError}from'./repository.ts';import {researcher,identity,sameOrigin,capability,sha256,authorized,type AuthEnv}from'./auth.ts';import {providerConfiguration}from'./providers.ts';import {exportSession,selectGroup}from'../shared/evidence.mjs';
import {localText,type LocalTextEnv}from'./local-text.ts';
import {localSpeech,type LocalSpeechEnv}from'./local-speech.ts';
import {crossAnalysis,type CrossEnv}from'./cross-analysis.ts';
import {DiagnosticStore,diagnosticContext,diagnosticsEndpoint,diagnosticPublicError}from'./diagnostics.mjs';
import {saveCustomStudy,listCustomStudies}from'./custom-studies.ts';
export interface Env extends AuthEnv,LocalTextEnv,LocalSpeechEnv,CrossEnv{DB:D1Database;CUSTOM_RESEARCH_ENABLED?:string;DEFAULT_STUDY_GUIDE_ID?:string;}
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'}});
async function body(request:Request){if(!request.headers.get('Content-Type')?.startsWith('application/json'))throw new ApiError(422,'JSON_REQUIRED');if(Number(request.headers.get('Content-Length'))>16384)throw new ApiError(413,'BODY_TOO_LARGE');const reader=request.body?.getReader();if(!reader)throw new ApiError(422,'INVALID_JSON');const parts:Uint8Array[]=[];let size=0;for(;;){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>16384){await reader.cancel();throw new ApiError(413,'BODY_TOO_LARGE');}parts.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const part of parts){bytes.set(part,offset);offset+=part.length;}try{const parsed=JSON.parse(new TextDecoder().decode(bytes));if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error();return parsed;}catch{throw new ApiError(422,'INVALID_JSON');}}
const validId=(x:unknown)=>typeof x==='string'&&/^[a-zA-Z0-9_-]{1,100}$/.test(x);
export async function api(request:Request,env:Env,ctx?:ExecutionContext){const started=Date.now(),store=env.DB?new DiagnosticStore(env.DB):null,diag=diagnosticContext({correlation_id:request.headers.get('X-Workflow-Id')});const write=async(event:any)=>{if(!store)return;const pending=store.record({...diag,source_session_ids:[...diag.source_session_ids]},event);if(ctx){ctx.waitUntil(pending);return;}await pending;};const priorityHint=request.method==='DELETE'||request.method!=='GET'&&(/\/(control|answers)$/.test(new URL(request.url).pathname)||new URL(request.url).pathname==='/api/research/service-control');if(!priorityHint)await write({stage:'request',status:'started',build_version:buildVersion});const response=await executeApi(request,env,diag,store,write);if(store)await write({stage:'request',status:response.ok?'succeeded':response.status===403||response.status===404?'denied':'failed',http_status:response.status,duration_ms:Date.now()-started,build_version:buildVersion});response.headers.set('X-Diagnostic-ID',diag.diagnostic_id);response.headers.set('X-Build-Version',buildVersion);return response;}
async function executeApi(request:Request,env:Env,diag:any,store:any,write:(event:any)=>Promise<unknown>){const url=new URL(request.url),path=url.pathname;try{
 if(!['GET','POST','PUT','PATCH','DELETE'].includes(request.method))throw new ApiError(405,'METHOD_NOT_ALLOWED');if(request.method!=='GET')sameOrigin(request,env);
 if(path==='/api/whoami'&&request.method==='GET'){const id=identity(request,env);if(!id||env.SITE_ACCESS_MODE!=='owner-private')throw new ApiError(403,'PRIVATE_IDENTITY_REQUIRED');return json({site_user_id:id,researcher:!!env.RESEARCHER_USER_ID&&id===env.RESEARCHER_USER_ID});}
 if(path==='/api/public/example'&&request.method==='GET')return json(gameplayExample());
 if(!env.DB)throw new ApiError(503,'DATABASE_UNAVAILABLE');const repo=new Repository(env.DB,write);
 let textService=localText(request,env,repo);
 if(path==='/api/public/study'&&request.method==='GET'){
  const selected=url.searchParams.get('guide_id')||builtinDefaultGuideId;if(!validId(selected))throw new ApiError(422,'INVALID_INPUT');
  const owner=!!env.RESEARCHER_USER_ID&&identity(request,env)===env.RESEARCHER_USER_ID;
  if(env.PUBLIC_DEMO_ENABLED==='true'&&!owner&&!textService?.local_engineering&&!isBuiltinGuideId(selected))throw new ApiError(404,'GUIDE_NOT_FOUND');
  const g=await repo.guide(selected);if(g?.kind==='custom'&&!isBuiltinGuide(g)&&env.CUSTOM_RESEARCH_ENABLED!=='true')throw new ApiError(404,'EXPERIMENT_DISABLED');if(!g)throw new ApiError(503,'GUIDE_UNAVAILABLE');
  const publicDemo=env.PUBLIC_DEMO_ENABLED==='true'&&isBuiltinGuide(g)&&!textService?.local_engineering;
  const service=publicDemo?localText(request,env,repo,true):textService,speech=localSpeech(request,env,repo,publicDemo);
  const control=await repo.budget(),availability=!service?'unavailable':!control.live_enabled?'paused':Date.now()>=Date.parse(providerConfiguration.limits.cutoff)?'closed':'ready',live=availability==='ready';
  return json({guide:g,live_enabled:live,public_demo:publicDemo,availability,local_synthetic_engineering:service?.local_engineering===true,local_speech_engineering:speech?.local_engineering===true,speech_ready:!!speech&&live,audio_max_seconds:speech?.local_engineering?30:90,allowed_origin:publicDemo||service?.local_engineering?'demo_live':null,consent_version:'consent-1',processing:publicDemo?'AI-powered fictional practice. Use invented, nonpersonal answers; this is not player research.':live?service?.local_engineering?'LOCAL SYNTHETIC ENGINEERING ONLY. Real provider calls; no human research.':'OpenAI text processing enabled after explicit private-site activation. Audio requires separate verified speech configuration.':'Live operation disabled. No new provider calls.'});
 }
 if(path==='/api/sessions'&&request.method==='POST'){
  const publicService=env.PUBLIC_DEMO_ENABLED==='true'?localText(request,env,repo,true):null;
  const control=await repo.budget();if(!control.live_enabled||(!textService&&!publicService)||Date.now()>=Date.parse(providerConfiguration.limits.cutoff))throw new ApiError(503,'LIVE_DISABLED');
  const b=await body(request);if(!validId(b.request_id)||!validId(b.guide_id)||!['real_self_report','demo_live'].includes(b.origin)||!['text','voice'].includes(b.initial_mode))throw new ApiError(422,'INVALID_INPUT');
  const publicDemo=!!publicService&&!textService?.local_engineering&&b.origin==='demo_live'&&isBuiltinGuideId(b.guide_id);
  if(!textService&&!publicDemo)throw new ApiError(403,'PUBLIC_DEMO_REQUIRED');
  if(publicDemo&&(Object.keys(b).sort().join(',')!=='consent,guide_id,initial_mode,origin,request_id'||!b.consent||['adult_confirmed','research_agreed','cloud_agreed'].some(k=>b.consent[k]!==true)))throw new ApiError(422,'INVALID_INPUT');
  if((textService?.local_engineering&&b.origin!=='demo_live')||(b.initial_mode!=='text'&&!localSpeech(request,env,repo,publicDemo)))throw new ApiError(403,'PROVIDER_SOURCE_NOT_ALLOWED');
  const tokenHash=await sha256(capability(request)),g=await repo.guide(b.guide_id);if(!g)throw new ApiError(404,'GUIDE_NOT_FOUND');if(g.kind==='custom'&&!isBuiltinGuide(g)&&env.CUSTOM_RESEARCH_ENABLED!=='true')throw new ApiError(404,'EXPERIMENT_DISABLED');const prior=await repo.findCreate(b.request_id);if(publicDemo&&prior&&!isPublicDemoSession(prior.session))throw new ApiError(404,'NOT_FOUND');if(!prior){if(publicDemo)await repo.rate('public-demo:create',providerConfiguration.limits.daily_sessions);await repo.creationQuota(await sha256(tokenHash+':'+b.request_id));}const created=await repo.create(g,b.consent,b.origin,b.initial_mode,tokenHash,b.request_id,await sha256(JSON.stringify(b)),publicDemo);Object.assign(diag,{route:'session.create',session_id:created.id,source_session_ids:[created.id]});return json({session:exportSession(created),state_version:created.state_version,current:created.current,guide:g},201);
 }
 if(path.startsWith('/api/research/')){
  const owner=researcher(request,env);
  diag.route=path.includes('activate')?'research.activation':path.includes('service-control')?'research.stop':path.includes('cleanup')?'research.cleanup':path.includes('analysis')?'research.analysis':'unknown';
  if(path==='/api/research/service-control'&&request.method==='PATCH'){const b=await body(request);if(b.live_enabled!==false)throw new ApiError(503,'LIVE_ENABLE_NOT_IMPLEMENTED');if(!validId(b.request_id))throw new ApiError(422,'INVALID_REQUEST');const control=await repo.updateBudget(c=>({...c,live_enabled:false,revision:c.revision+1,last_live_off_request:b.request_id}));await repo.recordDiagnostic({stage:'live_off',status:'succeeded'});return json({live_enabled:false,budget:control});}
  await repo.rate('research:'+owner+':'+(request.method==='GET'?'read':'write'),request.method==='GET'?120:60);
  if(path==='/api/research/diagnostics'){diag.route='diagnostics.read';return diagnosticsEndpoint(request,env,store,researcher);}
  if(path==='/api/research/provider/activate'&&request.method==='POST'){const b=await body(request);if(!validId(b.request_id)||b.live_enabled!==true)throw new ApiError(422,'INVALID_REQUEST');if(!textService)throw new ApiError(503,'PROVIDER_READINESS_REQUIRED');const budget=await textService.activate(b.request_id);await repo.recordDiagnostic({stage:'activation',status:'succeeded'});return json({live_enabled:budget.live_enabled,budget,audio_enabled:budget.live_enabled&&!!localSpeech(request,env,repo)});}
  if(path==='/api/research/custom-studies'){
   if(env.CUSTOM_RESEARCH_ENABLED!=='true')throw new ApiError(404,'EXPERIMENT_DISABLED');
   if(request.method==='GET')return json({enabled:true,guides:await listCustomStudies(env.DB,owner)});
   if(request.method==='POST'){const b=await body(request);if(Object.keys(b).sort().join(',')!=='confirmed,draft,request_id'||!validId(b.request_id)||b.confirmed!==true)throw new ApiError(422,'CONFIRMATION_REQUIRED');const result=await saveCustomStudy(env.DB,owner,b.request_id,b.draft);return json(result,result.replayed?200:201);}
   throw new ApiError(405,'METHOD_NOT_ALLOWED');
  }
  if(path==='/api/research/study/initialize'&&request.method==='POST')return json({guide:await repo.initialize(owner)});
  if(path==='/api/research/study/draft'&&request.method==='GET'){const study=await repo.study();return json({draft:study.draft,draft_revision:study.draft_revision,current_published_guide_id:study.current_published_guide_id});}
  if(path==='/api/research/study/draft'&&request.method==='PUT'){const b=await body(request);if(!validId(b.request_id)||!Number.isInteger(b.expected_draft_revision)||!b.draft)throw new ApiError(422,'INVALID_REQUEST');return json(await repo.editStudy(b.draft,b.expected_draft_revision,b.request_id));}
  if(path==='/api/research/study/publish'&&request.method==='POST'){const b=await body(request);if(!validId(b.request_id)||!Number.isInteger(b.expected_draft_revision))throw new ApiError(422,'INVALID_REQUEST');const study=await repo.study();return json(await repo.editStudy(study.draft,b.expected_draft_revision,b.request_id,true));}
  if(path==='/api/research/cleanup'&&request.method==='POST'){const result=await repo.cleanup();await store.cleanup();await repo.recordDiagnostic({stage:'cleanup',status:'succeeded'});return json(result);}
  if(path==='/api/research/analysis'&&request.method==='POST'){
   const b=await body(request);if(!validId(b.request_id)||!b.filter||!Array.isArray(b.session_ids)||!b.session_ids.length||b.session_ids.length>10||new Set(b.session_ids).size!==b.session_ids.length)throw new ApiError(422,'INVALID_SCOPE');
   const selected=selectGroup(await repo.list(),b.filter).filter((s:any)=>b.session_ids.includes(s.id));if(selected.length!==b.session_ids.length)throw new ApiError(422,'GROUP_MISMATCH');const service=textService&&crossAnalysis(env,repo,textService.local_engineering),live=!!service&&(await repo.budget()).live_enabled;if(selected.length<2)throw new ApiError(422,'CROSS_REQUIRES_TWO_SESSIONS');Object.assign(diag,{source_session_ids:selected.map((s:any)=>s.id)});const run=await repo.snapshot(selected,owner,{request_key:await sha256(owner+':cross:'+b.request_id),scope:'cross',status:live?'awaiting_provider':'blocked_live_disabled',payload:JSON.stringify({filter:b.filter,session_ids:[...b.session_ids].sort()})});if(!run)throw new ApiError(409,'STALE_ANALYSIS');diag.analysis_id=run.id;await repo.recordDiagnostic({stage:'analysis_prepare',status:'succeeded'});if(run.status==='ready')return json(run);return live?json(await service!.analyze(run,selected)):json(run,202);
  }
  const analysisPath=/^\/api\/research\/analysis\/([a-zA-Z0-9_-]{1,100})(?:\/findings\/([a-zA-Z0-9_-]{1,100}))?$/.exec(path);
  if(analysisPath){const [,runId,findingId]=analysisPath;if(request.method==='GET'&&!findingId){const run=await repo.analysis(runId);if(!run||['source_withdrawn','source_expired'].includes(run.status))throw new ApiError(404,'NOT_FOUND');return json(run);}if(request.method==='PATCH'&&findingId){const b=await body(request);if(!validId(b.request_id)||!Number.isInteger(b.expected_revision))throw new ApiError(422,'INVALID_REQUEST');return json(await repo.review(runId,findingId,b,owner));}}
  if(path==='/api/research/fixtures'&&request.method==='POST'){const b=await body(request);if(!validId(b.request_id)||!validId(b.guide_id))throw new ApiError(422,'INVALID_INPUT');const g=await repo.guide(b.guide_id);if(!g)throw new ApiError(404,'GUIDE_NOT_FOUND');if(g.kind==='custom'&&!isBuiltinGuide(g)&&env.CUSTOM_RESEARCH_ENABLED!=='true')throw new ApiError(404,'EXPERIMENT_DISABLED');const token=capability(request);const s=await repo.create(g,b.consent,'demo_fixture',b.mode||'text',await sha256(token),b.request_id,await sha256(JSON.stringify(b)));return json({session:s},201);}
  if(path==='/api/research/sessions'&&request.method==='GET')return json({sessions:await repo.list()});
  if(path==='/api/research/export'&&request.method==='GET'){const filter={guide_id:url.searchParams.get('guide_id'),origin:url.searchParams.get('origin'),mode_group:url.searchParams.get('mode_group'),mode_basis:url.searchParams.get('mode_basis')||'eligible'};if(!filter.guide_id||!filter.origin||!filter.mode_group)throw new ApiError(422,'GROUP_REQUIRED');return json({schema_version:'1.1',filter,sessions:selectGroup(await repo.list(),filter).map(exportSession)});}
  if(path==='/api/research/service-control'&&request.method==='GET'){const budget=await repo.budget();return json({...providerConfiguration,live_enabled:budget.live_enabled&&!!textService&&Date.now()<Date.parse(providerConfiguration.limits.cutoff),transport:textService?'bounded_explicit_gates':'disabled',actual_calls:await repo.providerAttemptCount(),speech_ready:!!localSpeech(request,env,repo)&&budget.live_enabled,budget});}
  if(path==='/api/research/service-control'&&request.method==='PATCH'){const b=await body(request);if(b.live_enabled!==false)throw new ApiError(503,'LIVE_ENABLE_NOT_IMPLEMENTED');if(!validId(b.request_id))throw new ApiError(422,'INVALID_REQUEST');const control=await repo.updateBudget(c=>({...c,live_enabled:false,revision:c.revision+1,last_live_off_request:b.request_id}));return json({live_enabled:false,budget:control});}
  throw new ApiError(404,'ROUTE_NOT_FOUND');
 }
 const match=/^\/api\/sessions\/([a-zA-Z0-9_-]{1,100})(?:\/(answers|control|exposures|decision|stt|tts|analysis)(?:\/([a-zA-Z0-9_-]{1,100}))?)?$/.exec(path);if(!match)throw new ApiError(404,'ROUTE_NOT_FOUND');const [,id,operation,answerId]=match;const row=await repo.get(id);
 // Deletion retry remains possible only with the original matching capability.
 if(request.method==='DELETE'&&!operation&&row?.session.status==='withdrawn'){if(await sha256(capability(request))!==row.token_hash)throw new ApiError(404,'NOT_FOUND');return json({status:'withdrawn'});}
 const s=await authorized(request,env,row,request.method==='GET'||request.method==='PATCH'||request.method==='DELETE',request.method==='DELETE'&&!operation);
 const publicDemo=isPublicDemoSession(s)&&env.PUBLIC_DEMO_ENABLED==='true';if(publicDemo)textService=localText(request,env,repo,true);
 Object.assign(diag,{route:'session.'+(operation==='answers'?'answer':operation==='exposures'?'exposure':operation||'control'),session_id:s.id,question_id:s.current,source_session_ids:[s.id]});
 const priorityBody=(request.method==='DELETE'&&!operation||request.method==='POST'&&['control','answers'].includes(operation))?await body(request):null;
 const priority=request.method==='DELETE'&&!operation||request.method==='POST'&&operation==='control'&&['pause','end','skip_topic'].includes(priorityBody?.action)||request.method==='POST'&&operation==='answers'&&priorityBody?.response_status==='refused';
 if(!priority)await repo.rate('session:'+row!.token_hash+':'+(request.method==='GET'?'read':'write'),request.method==='GET'?120:60);
 if(request.method==='GET'&&!operation)return json({session:exportSession(s),state_version:s.state_version,current:s.current,phase:s.phase,step:s.step,task:s.task?{...s.task,provider_attempt:await repo.decisionAttempt(s.task.id)}:null,guide:await repo.guide(s.guide_id)});
 if(operation==='analysis'&&request.method==='POST'){const b=await body(request);if(publicDemo&&Object.keys(b).sort().join(',')!=='request_id')throw new ApiError(422,'INVALID_REQUEST');if(!validId(b.request_id))throw new ApiError(422,'INVALID_REQUEST');const live=!!textService&&(await repo.budget()).live_enabled;const run=await repo.snapshot([s],s.id,{request_key:await sha256(s.id+':single:'+b.request_id),scope:'single',status:live?'awaiting_provider':'blocked_live_disabled',resume_pending_single:live,payload:JSON.stringify({session_id:s.id})});if(!run)throw new ApiError(409,'STALE_ANALYSIS');diag.analysis_id=run.id;await repo.recordDiagnostic({stage:'analysis_prepare',status:'succeeded'});return json(live?await textService!.analyze(run,[s]):run,live?200:202);}
 if(operation==='analysis'&&!answerId&&request.method==='GET')return json({analysis:await repo.savedSingleAnalysis(s.id)});
 if(operation==='analysis'&&answerId&&request.method==='GET'){const run=await repo.analysis(answerId);if(!run||run.scope!=='single'||run.requester_id!==s.id||run.input_manifest.length!==1||run.input_manifest[0].session_id!==s.id)throw new ApiError(404,'NOT_FOUND');return json(run);}
 if(operation==='decision'&&request.method==='POST'){if(!textService||!(await repo.budget()).live_enabled)throw new ApiError(503,'LIVE_DISABLED');const b=await body(request);if(!validId(b.task_id))throw new ApiError(422,'INVALID_REQUEST');const g=await repo.guide(s.guide_id);if(!g)throw new ApiError(503,'GUIDE_UNAVAILABLE');const saved=await textService.decide(s,g,b.task_id);return json({session:exportSession(saved),state_version:saved.state_version,current:saved.current,phase:saved.phase,step:saved.step,task:saved.task});}
 if(['stt','tts'].includes(operation)&&request.method==='POST'){const speech=localSpeech(request,env,repo,publicDemo);if(!speech||!(await repo.budget()).live_enabled)throw new ApiError(503,'LIVE_DISABLED');if(operation==='tts'){const b=await body(request);if(!validId(b.question_id)||!validId(b.request_id))throw new ApiError(422,'INVALID_REQUEST');const audio=await speech.tts(s,b.question_id);return new Response(audio,{headers:{'Content-Type':'audio/mpeg','Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Source-Origin':'provider_tts_'+s.origin}});}if(!request.headers.get('Content-Type')?.startsWith('audio/wav'))throw new ApiError(422,'PCM_WAV_REQUIRED');const qid=request.headers.get('X-Question-Id'),rid=request.headers.get('X-Request-Id');if(!validId(qid)||!validId(rid))throw new ApiError(422,'INVALID_REQUEST');const reader=request.body?.getReader();if(!reader)throw new ApiError(422,'AUDIO_REQUIRED');const chunks:Uint8Array[]=[];let n=0;while(true){const next=await reader.read();if(next.done)break;n+=next.value.length;if(n>8*1024*1024){await reader.cancel();throw new ApiError(413,'AUDIO_LIMIT');}chunks.push(next.value);}const bytes=new Uint8Array(n);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}return json(await speech.stt(s,qid!,rid!,bytes.buffer));}
 const g=await repo.guide(s.guide_id);if(!g)throw new ApiError(503,'GUIDE_UNAVAILABLE');const b=priorityBody||await body(request);let command:any;
 if(request.method==='DELETE'&&!operation)command={type:'withdraw'};
 else if(operation==='answers'&&request.method==='POST'){if(b.transcript_source_task_id&&!s.receipts?.some((r:any)=>r.id===b.request_id)){if(typeof b.transcript_source_task_id!=='string'||!b.transcript_source_task_id.startsWith('stt-'+s.id+'-')||!await repo.hasTranscriptionTask(b.transcript_source_task_id,s,b.question_id))throw new ApiError(422,'INVALID_TRANSCRIPT_PROVENANCE');}command={type:'answer',question_id:b.question_id,response_status:b.response_status,final_text:b.final_text,input_mode:b.input_mode,edited_transcript:b.edited_transcript,transcript_source_task_id:b.transcript_source_task_id};}
 else if(operation==='answers'&&answerId&&request.method==='PATCH')command={type:'correct',answer_id:answerId,answer_revision:b.answer_revision,final_text:b.final_text,reason:b.reason};
 else if(operation==='control'&&request.method==='POST'){if(!['pause','resume','end','continue','skip_topic','switch_mode'].includes(b.action))throw new ApiError(422,'INVALID_CONTROL');command={type:b.action,mode:b.mode};}
 else if(operation==='exposures'&&request.method==='POST')command={type:'exposure',question_id:b.question_id,channel:b.channel,state:b.state,attempt_id:b.attempt_id};
 else throw new ApiError(404,'ROUTE_NOT_FOUND');
 if(!validId(b.request_id)||!Number.isInteger(b.expected_state_version))throw new ApiError(422,'INVALID_REQUEST');diag.request_id=b.request_id;command={...command,request_id:b.request_id,expected_version:b.expected_state_version};const r=priority?await repo.safety(s.id,g,command):await repo.mutate(s,g,command);return json({session:exportSession(r.session),state_version:r.session.state_version,replayed:r.replayed,current:r.session.current,phase:r.session.phase,step:r.session.step,task:r.session.task});
 }catch(error){const e=error as any;const code=e.code||'INTERNAL_ERROR';const conflict=['STATE_CONFLICT','IDEMPOTENCY_MISMATCH','QUESTION_CONFLICT','TERMINATED','STALE_TASK','ANSWER_CONFLICT','DRAFT_CONFLICT','REVIEW_CONFLICT','STALE_ANALYSIS','ANALYSIS_NOT_READY'];const status=e.status|| (conflict.includes(code)?409:code==='EXPIRED'||code==='WITHDRAWN'?410:code==='INTERNAL_ERROR'?503:422);if(store)await write({stage:'request',status:'failed',http_status:status,provider_attempt_id:e.provider_call_id,failure:{error:e},build_version:buildVersion});return json({error:{code,message:code.replaceAll('_',' ').toLowerCase(),retryable:status===409||status===429||status===503,diagnostic_id:diagnosticPublicError(diag).diagnostic_id}},status);}}
export default {fetch:api};
