import{isPublicDemoSession}from'./public-demo.ts';
import{singleAnalysisInput,boundedTextRequest}from'./single-analysis-input.ts';
import {Repository,ApiError}from'./repository.ts';import {BoundedTransport}from'./bounded-transport.ts';import {decisionSchemaFor,analysisSchemaFor,decisionInput,analysisInput,validateDecision,validateAnalysis}from'./text-protocol.ts';import {reserveCall}from'../shared/budget.mjs';
import {identity,type AuthEnv}from'./auth.ts';
import {limits}from'../shared/session.mjs';
export interface LocalTextEnv extends AuthEnv {PUBLIC_DEMO_ENABLED?:string;LOCAL_ENGINEERING_TEXT?:boolean;LOCAL_OPENAI_API_KEY?:string;LOCAL_PROVIDER_FETCH?:typeof fetch;HOSTED_PROVIDER_ENABLED?:string;HOSTED_IDENTITY_VERIFIED?:string;PROVIDER_PRICING_VERIFIED?:string;OPENAI_API_KEY?:string;PRIOR_SPEND_UPPER_MICRO_USD?:string;PRIOR_UNKNOWN_MICRO_USD?:string;}
const PRICE='sol-local-synthetic-phase-20261004';
export function localText(request:Request,env:LocalTextEnv,repo:Repository,publicDemo=false){
 const u=new URL(request.url),local=env.LOCAL_ENGINEERING_TEXT===true&&['localhost','127.0.0.1','[::1]'].includes(u.hostname)&&!!env.LOCAL_OPENAI_API_KEY;
 const hosted=env.HOSTED_PROVIDER_ENABLED==='true'&&env.HOSTED_IDENTITY_VERIFIED==='true'&&env.PROVIDER_PRICING_VERIFIED==='sol-standard-2026-10-04-engineering-buffer'&&env.AUTH_MODE==='sites-dispatch'&&env.SITE_ACCESS_MODE==='owner-private'&&!!env.RESEARCHER_USER_ID&&(identity(request,env)===env.RESEARCHER_USER_ID||(publicDemo&&env.PUBLIC_DEMO_ENABLED==='true'))&&env.APP_ORIGIN===u.origin&&!!env.OPENAI_API_KEY&&/^\d+$/.test(env.PRIOR_SPEND_UPPER_MICRO_USD||'')&&/^\d+$/.test(env.PRIOR_UNKNOWN_MICRO_USD||'');
 if(!local&&!hosted)return null;
 const ledger={reserve:(r:any)=>repo.updateBudget(c=>{if(local){const phase=c.reservations.filter((x:any)=>x.price_version===PRICE).reduce((n:number,x:any)=>n+(x.status==='settled'?(x.accounted_micro_usd??x.actual_micro_usd??x.ceiling_micro_usd):x.ceiling_micro_usd),0);if(phase+r.ceiling_micro_usd>1000000)throw new ApiError(503,'ENGINEERING_PHASE_COST_CAP');}return reserveCall(c,r);}),settle:repo.settle.bind(repo),claimAttempt:repo.claimAttempt.bind(repo),finishAttempt:repo.finishAttempt.bind(repo),pauseLive:repo.pauseLive.bind(repo),recordDiagnostic:repo.recordDiagnostic.bind(repo)};
 const transport=new BoundedTransport(ledger,{enabled:true,identity_verified:true,cloud_consent_verified:true,api_key:local?env.LOCAL_OPENAI_API_KEY!:env.OPENAI_API_KEY!,price_version:local?PRICE:'sol-hosted-approved-engineering-buffer-20261004',stt_price_ceiling_verified:false,reservation_basis:'engineering_buffer',inputTokenBound:async payload=>boundedTextRequest(payload,local)},local?env.LOCAL_PROVIDER_FETCH:undefined);
 const eligible=(s:any)=>{if(publicDemo&&!isPublicDemoSession(s))throw new ApiError(403,'PUBLIC_DEMO_REQUIRED');if((local?s.origin!=='demo_live':!['demo_live','real_self_report'].includes(s.origin))||s.consent?.cloud_agreed!==true)throw new ApiError(403,'PROVIDER_SOURCE_NOT_ALLOWED');};
 return {
  local_engineering:local,
  async activate(requestId:string){if(Date.now()>=Date.parse(limits.cutoff)){await repo.pauseLive();throw new ApiError(503,'CALL_CUTOFF');}if(local)throw new ApiError(403,'HOSTED_ACTIVATION_ONLY');const spend=Number(env.PRIOR_SPEND_UPPER_MICRO_USD),unknown=Number(env.PRIOR_UNKNOWN_MICRO_USD);if(!Number.isSafeInteger(spend)||!Number.isSafeInteger(unknown)||spend+unknown>20000000)throw new ApiError(422,'INVALID_CARRYOVER');return repo.updateBudget(c=>{if(c.last_live_on_request===requestId)return c;const next=structuredClone(c);if(!next.carryover_initialized){if(next.reservations.length||next.known_spend_micro_usd)throw new ApiError(409,'CARRYOVER_REQUIRES_RECONCILIATION');next.known_spend_micro_usd=spend;if(unknown)next.reservations.push({task_id:'pre-host-unknown-carryover',session_id:'historical-validation',operation:'decision',price_version:'pre-host-carryover',ceiling_micro_usd:unknown,status:'unknown',lease_until:0,lease_released:true});next.carryover_initialized=true;}next.live_enabled=true;next.last_live_on_request=requestId;next.revision++;return next;});},
  async decide(s:any,g:any,taskId:string){eligible(s);if(s.receipts.some((r:any)=>r.id==='decision-'+taskId))return s;if(s.status!=='active'||s.step!=='deciding'||s.task?.id!==taskId)throw new ApiError(409,'STALE_TASK');const task=s.task;await repo.recordDiagnostic({stage:'decision_prepare',status:'succeeded',operation:'decision',state_version:s.state_version,content_revision:s.content_revision,question_id:s.current});
   const value:any=await transport.text({task_id:task.id,operation:'decision',session_id:s.id,content_revision:s.content_revision},decisionInput(s,g),decisionSchemaFor(g),async v=>{try{const accepted=validateDecision(v,s,g);await repo.recordDiagnostic({stage:'decision_validate',status:'succeeded',operation:'decision',content_revision:s.content_revision});return accepted;}catch(error){await repo.recordDiagnostic({stage:'decision_validate',status:'failed',operation:'decision',failure:{error,phase:'schema'}});throw error;}});
   const row=await repo.get(s.id);if(!row||row.session.status!=='active'||row.session.content_revision!==s.content_revision||row.session.task?.id!==task.id)throw new ApiError(409,'STALE_TASK');
   return (await repo.mutate(row.session,g,{type:'decision',request_id:'decision-'+task.id,expected_version:row.session.state_version,task_id:task.id,input_content_revision:s.content_revision,action:value.action,theme_id:value.theme_id,question_text:value.question_text})).session;
  },
  async analyze(run:any,sessions:any[]){sessions.forEach(eligible);if(run.status==='ready')return run;if(run.stale||run.status!=='awaiting_provider')throw new ApiError(409,'STALE_ANALYSIS');const s=sessions[0];if(await repo.analysisAttempt('analysis-'+run.id))throw new ApiError(409,'ATTEMPT_ALREADY_CLAIMED');const value=await transport.text({task_id:'analysis-'+run.id,operation:'analysis',session_id:s.id,content_revision:s.content_revision},singleAnalysisInput(sessions),analysisSchemaFor(sessions),v=>validateAnalysis(v,sessions));await repo.recordDiagnostic({stage:'analysis_validate',status:'succeeded',operation:'analysis',analysis_id:run.id});const saved=await repo.commitCandidates(run.id,value,'provider');await repo.recordDiagnostic({stage:'analysis_persist',status:'succeeded',operation:'analysis',analysis_id:run.id});return saved;}
 };
}
