import{isPublicDemoSession}from'./public-demo.ts';
import {Repository,ApiError}from'./repository.ts';import {reserveCall}from'../shared/budget.mjs';import {prepareStoredQuestionSpeech,prepareTranscription}from'./speech-preparation.ts';import {validateMp3}from'./mp3-validation.ts';import {sha256}from'./auth.ts';import {models}from'../shared/session.mjs';
import {identity}from'./auth.ts';import type {LocalTextEnv}from'./local-text.ts';
export interface LocalSpeechEnv extends LocalTextEnv {LOCAL_ENGINEERING_SPEECH?:boolean;HOSTED_SPEECH_ENABLED?:string;SPEECH_PRICING_VERIFIED?:string;}
import {providerErrorCode as allowProviderCode,providerErrorType,providerErrorParam,providerRequestId as allowRequestId}from'./provider-metadata.mjs';
const PRICE='speech-engineering-once-20261004',cache=new Map<string,{fingerprint:string;value:any;expires_at:number;bytes:number}>();
export function localSpeech(request:Request,env:LocalSpeechEnv,repo:Repository,publicDemo=false){const u=new URL(request.url),local=env.LOCAL_ENGINEERING_SPEECH===true&&!!env.LOCAL_OPENAI_API_KEY&&['localhost','127.0.0.1','[::1]'].includes(u.hostname),hosted=env.HOSTED_PROVIDER_ENABLED==='true'&&env.HOSTED_SPEECH_ENABLED==='true'&&env.HOSTED_IDENTITY_VERIFIED==='true'&&env.SPEECH_PRICING_VERIFIED==='selected-speech-2026-10-04-engineering-buffer'&&env.AUTH_MODE==='sites-dispatch'&&env.SITE_ACCESS_MODE==='owner-private'&&!!env.RESEARCHER_USER_ID&&(identity(request,env)===env.RESEARCHER_USER_ID||(publicDemo&&env.PUBLIC_DEMO_ENABLED==='true'))&&env.APP_ORIGIN===u.origin&&!!env.OPENAI_API_KEY;if(!local&&!hosted)return null;
 const send=(local?env.LOCAL_PROVIDER_FETCH:undefined)||fetch,key=local?env.LOCAL_OPENAI_API_KEY!:env.OPENAI_API_KEY!;
 const check=async(s:any,qid:string)=>{const row=await repo.get(s.id);if(!row||(publicDemo&&!isPublicDemoSession(row.session))||row.session.status!=='active'||row.session.current!==qid||row.session.mode!=='voice'||row.session.content_revision!==s.content_revision||(row.session.media_generation||0)!==(s.media_generation||0)||(local?row.session.origin!=='demo_live':!['demo_live','real_self_report'].includes(row.session.origin))||row.session.consent?.cloud_agreed!==true)throw new ApiError(409,'STALE_AUDIO');};
 const execute=async(s:any,operation:'tts'|'stt',task:string,fingerprint:string,make:()=>RequestInit,seconds?:number)=>{
  for(const [k,c]of cache)if(c.expires_at<Date.now())cache.delete(k);const prior=cache.get(task);if(prior){if(prior.fingerprint!==fingerprint)throw new ApiError(409,'IDEMPOTENCY_MISMATCH');return prior.value;}
  const id=crypto.randomUUID();await repo.updateBudget(c=>{if(local&&c.reservations.some((r:any)=>r.price_version===PRICE&&r.operation===operation))throw new ApiError(503,'AUDIO_ENGINEERING_ATTEMPT_LIMIT');return reserveCall(c,{task_id:id,session_id:s.id,operation,price_version:local?PRICE:'speech-hosted-approved-engineering-buffer-20261004',ceiling_micro_usd:1000000,...seconds?{audio_seconds:seconds}:{}});});
  if(!await repo.claimAttempt(id,{task_id:task,session_id:s.id,operation,content_revision:s.content_revision},models[operation])){await repo.settle(id,0,{confirmed_finished:true});throw new ApiError(409,'ATTEMPT_ALREADY_CLAIMED');}
  const started=Date.now();let phase='fetch_exception',httpStatus:number|null=null,providerRequestId:string|null=null,providerErrorCode:string|null=null;await repo.recordDiagnostic({stage:operation==='stt'?'stt_validate':'tts_prepare',status:'succeeded',operation,question_id:s.current,content_revision:s.content_revision,media_generation:s.media_generation||0});await repo.recordDiagnostic({stage:'provider_dispatch',status:'started',operation,provider_attempt_id:id});let finished=false;try{const init=make();const res=await send('https://api.openai.com/v1/audio/'+(operation==='tts'?'speech':'transcriptions'),{...init,method:'POST',headers:{...init.headers,Authorization:'Bearer '+key},signal:AbortSignal.timeout(30000)});
   httpStatus=res.status;providerRequestId=res.headers.get('x-request-id');phase='body_read_exception';if(!res.ok){const data:any=await res.json().catch(()=>({}));finished=true;phase='upstream_http';providerErrorCode=allowProviderCode(data.error?.code);await repo.finishAttempt(id,'http_error',{http_status:res.status,error_code:providerErrorCode,error_type:providerErrorType(data.error?.type),error_param:providerErrorParam(data.error?.param),provider_request_id:allowRequestId(providerRequestId)});throw new ApiError(res.status===429?429:502,'SPEECH_PROVIDER_HTTP_ERROR');}
   let value:any,metadata:any={reservation_basis:'engineering_buffer',actual_billed_cost_verified:false,session_id:s.id,question_id:s.current,input_content_revision:s.content_revision,media_generation:s.media_generation||0};
   if(operation==='tts'){const reader=res.body?.getReader();if(!reader)throw new ApiError(502,'AUDIO_RESPONSE_EMPTY');const chunks:Uint8Array[]=[];let n=0;while(true){const next=await reader.read();if(next.done)break;n+=next.value.length;if(n>8*1024*1024){await reader.cancel();throw new ApiError(502,'AUDIO_LIMIT');}chunks.push(next.value);}finished=true;const out=new Uint8Array(n);let offset=0;for(const c of chunks){out.set(c,offset);offset+=c.length;}value=out.buffer;metadata={...metadata,...validateMp3(value,local?30:90)};
   }else{phase='parse_exception';const data:any=await res.json();finished=true;phase='schema';if(typeof data.text!=='string'||data.text.length>1500)throw new ApiError(502,'TRANSCRIPT_LIMIT');value={text:data.text,draft:true,confirmed:false,source:'provider_stt',provider_task_id:task,record_origin:s.origin,audio_seconds:seconds};metadata={...metadata,audio_seconds:seconds,usage:data.usage&&typeof data.usage==='object'?Object.fromEntries(Object.entries(data.usage).filter(([k,v])=>['input_tokens','output_tokens','total_tokens','seconds'].includes(k)&&typeof v==='number'&&Number.isFinite(v))):null,estimated_duration_price_usd:(seconds||0)/60*0.0045,estimate_not_bill:true};}
   await repo.settle(id,null,{confirmed_finished:true});await repo.finishAttempt(id,'completed_cost_unknown',{...metadata,provider_request_id:allowRequestId(providerRequestId),http_status:httpStatus});await repo.recordDiagnostic({stage:'provider_response',status:'succeeded',operation,provider_attempt_id:id,http_status:httpStatus,provider_request_id:providerRequestId,duration_ms:Date.now()-started});if(operation==='stt')await repo.recordDiagnostic({stage:'stt_draft',status:'succeeded',operation,provider_attempt_id:id,question_id:s.current});cache.set(task,{fingerprint,value,expires_at:Math.min(Date.parse(s.expires_at),Date.now()+600000),bytes:value instanceof ArrayBuffer?value.byteLength:JSON.stringify(value).length});while(cache.size>20||[...cache.values()].reduce((n,c)=>n+c.bytes,0)>32*1024*1024)cache.delete(cache.keys().next().value!);return value;
  }catch(e){await repo.recordDiagnostic({stage:'provider_response',status:'failed',operation,provider_attempt_id:id,duration_ms:Date.now()-started,failure:{error:e,phase,http_status:httpStatus,provider_request_id:providerRequestId,provider_error_code:providerErrorCode}});await repo.settle(id,null,{confirmed_finished:finished});if(!finished){await repo.finishAttempt(id,'transport_unknown',null);}await repo.pauseLive();if(e instanceof ApiError){Object.assign(e,{provider_call_id:id});throw e;}throw Object.assign(new ApiError(502,'SPEECH_PROVIDER_UNAVAILABLE'),{provider_call_id:id});}
 };
 return {local_engineering:local,async tts(s:any,qid:string){await check(s,qid);const prepared=prepareStoredQuestionSpeech(s,qid);if(local&&prepared.input.length>120)throw new ApiError(422,'ENGINEERING_QUESTION_LIMIT');const fingerprint=await sha256(prepared.input);const bytes=await execute(s,'tts','tts-'+s.id+'-'+qid+'-g'+(s.media_generation||0),fingerprint,()=>({headers:{'Content-Type':'application/json'},body:JSON.stringify({model:prepared.model,voice:prepared.voice,response_format:prepared.response_format,input:prepared.input})}));await check(s,qid);return bytes;},async stt(s:any,qid:string,requestId:string,audio:ArrayBuffer){await check(s,qid);const prepared=prepareTranscription(s,audio);if(local&&prepared.seconds>30)throw new ApiError(422,'ENGINEERING_AUDIO_LIMIT');const hash=await crypto.subtle.digest('SHA-256',audio),fingerprint=[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('');const value=await execute(s,'stt','stt-'+s.id+'-'+requestId+'-g'+(s.media_generation||0),fingerprint,()=>{const form=new FormData();form.set('model',models.stt);form.set('file',new Blob([audio],{type:'audio/wav'}),'synthetic-or-explicit-recording.wav');form.set('language','en');form.set('response_format','json');return {body:form};},prepared.seconds);await check(s,qid);return value;}};
}

