import{publicDemoVersion,isPublicDemoSession}from'./public-demo.ts';
import {buildVersion}from'./build-info.ts';
import {builtinGuideById,isBuiltinGuide}from'../shared/default-guide.mjs';
import {sessionTopicIds}from'../shared/custom-study.mjs';
import {transition,publish,createSession,draft} from '../shared/session.mjs';
import {manifest,exportSession,stale,selectGroup,denominators} from '../shared/evidence.mjs';
import {initialBudget,reserveCall,settleCall,reserveSessionEntry}from'../shared/budget.mjs';
import {validateCandidates}from'../shared/candidates.mjs';
export class ApiError extends Error{constructor(public status:number,public code:string){super(code);}}
export class Repository{
 constructor(private db:D1Database,private diagnosticWriter?:(event:any)=>Promise<unknown>){}
 async recordDiagnostic(event:any){try{await this.diagnosticWriter?.({build_version:buildVersion,retry_count:0,...event});}catch{}}
 async mutate(s:any,g:any,command:any){const stage=command.type==='answer'||command.type==='correct'?'answer_save':command.type==='decision'?'decision_persist':['pause','resume','end','withdraw'].includes(command.type)?command.type:command.type==='skip_topic'?'refusal':null;const versions={state_version:s.state_version,content_revision:s.content_revision,media_generation:s.media_generation||0,question_id:command.question_id||s.current};if(command.type==='answer'&&command.transcript_source_task_id)await this.recordDiagnostic({stage:'transcript_confirmation',status:'succeeded',...versions});if(stage&&!['pause','end','withdraw','refusal'].includes(stage)&&!(command.type==='answer'&&command.response_status==='refused'))await this.recordDiagnostic({stage,status:'started',...versions});try{const result=await this.mutateCore(s,g,command);if(stage)await this.recordDiagnostic({stage,status:result.replayed?'replayed':'succeeded',...versions,state_version:result.session.state_version,content_revision:result.session.content_revision,answer_id:result.session.answers?.at(-1)?.id});if(command.type==='answer')await this.recordDiagnostic({stage:'answer_submit',status:result.replayed?'replayed':'succeeded',...versions,answer_id:result.session.answers?.at(-1)?.id});return result;}catch(error){if(stage)await this.recordDiagnostic({stage,status:'failed',...versions,failure:{error}});throw error;}}

 async get(id:string){const row=await this.db.prepare('SELECT aggregate_json,token_hash,create_payload_hash FROM sessions WHERE id=?').bind(id).first<{aggregate_json:string;token_hash:string;create_payload_hash:string}>();return row?{session:JSON.parse(row.aggregate_json),token_hash:row.token_hash,payload_hash:row.create_payload_hash}:null;}
 async decisionAttempt(taskId:string){const row=await this.db.prepare("SELECT id,status FROM provider_calls WHERE task_id=? AND operation='decision'").bind(taskId).first<any>();return row?{claimed:true,status:row.status,provider_call_id:row.id}:null;}
 async analysisAttempt(taskId:string){const row=await this.db.prepare("SELECT id,status FROM provider_calls WHERE task_id=? AND operation='analysis'").bind(taskId).first<any>();return row?{claimed:true,status:row.status,provider_call_id:row.id}:null;}
 async providerAttemptCount(){const row=await this.db.prepare('SELECT COUNT(*) AS count FROM provider_calls').first<{count:number}>();return Number(row?.count||0);}
 async findCreate(id:string){const row=await this.db.prepare('SELECT id FROM sessions WHERE create_request_id=?').bind(id).first<{id:string}>();return row?this.get(row.id):null;}
 async guide(id?:string){if(id){const row=await this.db.prepare('SELECT guide_json FROM guide_versions WHERE id=?').bind(id).first<{guide_json:string}>();const builtin=builtinGuideById(id);if(builtin){if(row&&JSON.stringify(JSON.parse(row.guide_json))!==JSON.stringify(builtin))throw new ApiError(503,'BUILTIN_GUIDE_CONFLICT');return builtin;}return row?JSON.parse(row.guide_json):null;}const row=await this.db.prepare("SELECT guide_json FROM guide_versions WHERE study_id='study-delta-force' ORDER BY version DESC LIMIT 1").first<{guide_json:string}>();return row?JSON.parse(row.guide_json):null;}
 private async persistBuiltinGuide(g:any){
  if(!isBuiltinGuide(g))return;
  if(JSON.stringify(g)!==JSON.stringify(builtinGuideById(g.id)))throw new ApiError(503,'BUILTIN_GUIDE_CONFLICT');
  await this.db.batch([
   this.db.prepare('INSERT OR IGNORE INTO studies (id,owner_site_user_id,title,draft_json,draft_revision,current_published_guide_id,created_at) VALUES (?,?,?,?,0,?,?)').bind(g.study_id,'system-builtin',g.title,JSON.stringify({builtin_template_version:g.builtin_template_version}),g.id,g.published_at),
   this.db.prepare('INSERT OR IGNORE INTO guide_versions (id,study_id,version,guide_json,published_at) VALUES (?,?,?,?,?)').bind(g.id,g.study_id,g.version,JSON.stringify(g),g.published_at)
  ]);
  await this.guide(g.id);
 }
 async initialize(owner:string){const existing=await this.guide();if(existing)return existing;const g=publish(draft);const studyId='study-delta-force';await this.db.batch([this.db.prepare('INSERT OR IGNORE INTO studies (id,owner_site_user_id,title,draft_json,draft_revision,current_published_guide_id,created_at) VALUES (?,?,?,?,0,?,?)').bind(studyId,owner,draft.title,JSON.stringify(draft),g.id,g.published_at),this.db.prepare('INSERT OR IGNORE INTO guide_versions (id,study_id,version,guide_json,published_at) VALUES (?,?,?,?,?)').bind(g.id,studyId,1,JSON.stringify(g),g.published_at)]);return this.guide();}
 async create(g:any,consent:any,origin:string,mode:string,tokenHash:string,requestId:string,payloadHash:string,publicDemo=false){
  const prior=await this.findCreate(requestId);if(prior){if(prior.token_hash!==tokenHash)throw new ApiError(404,'NOT_FOUND');if(prior.payload_hash!==payloadHash)throw new ApiError(409,'IDEMPOTENCY_MISMATCH');if(prior.session.status==='withdrawn')throw new ApiError(410,'WITHDRAWN');if(Date.parse(prior.session.expires_at)<=Date.now())throw new ApiError(410,'EXPIRED');return prior.session;}
  const s:any=createSession(g,consent,{origin,mode});if(publicDemo){s.public_demo_version=publicDemoVersion;if(!isPublicDemoSession(s))throw new ApiError(403,'PUBLIC_DEMO_REQUIRED');}
  await this.persistBuiltinGuide(g);
  const result=await this.db.prepare('INSERT OR IGNORE INTO sessions (id,study_id,guide_id,origin,token_hash,create_request_id,create_payload_hash,state_version,content_revision,evidence_revision,status,expires_at,aggregate_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(s.id,g.kind==='custom'?g.study_id:'study-delta-force',g.id,origin,tokenHash,requestId,payloadHash,s.state_version,s.content_revision,s.evidence_revision,s.status,s.expires_at,JSON.stringify(s)).run();
  if(result.meta.changes!==1){const other=await this.findCreate(requestId);if(!other||other.token_hash!==tokenHash)throw new ApiError(404,'NOT_FOUND');if(other.payload_hash!==payloadHash)throw new ApiError(409,'IDEMPOTENCY_MISMATCH');return other.session;}return s;
 }
 private async mutateCore(s:any,g:any,command:any){const result=transition(s,g,command);if(result.replayed)return result;
  const next=result.session;const update=this.db.prepare('UPDATE sessions SET aggregate_json=?,state_version=?,content_revision=?,evidence_revision=?,status=? WHERE id=? AND state_version=? AND status=?').bind(JSON.stringify(next),next.state_version,next.content_revision,next.evidence_revision,next.status,s.id,s.state_version,s.status);
  // Conditional derivative clearing shares the transaction and succeeds only if this CAS did.
  const clear=this.db.prepare("UPDATE analysis_runs SET status='source_withdrawn',result_json=NULL,input_manifest_json='[]',operations_json='[]',revision=revision+1 WHERE id IN (SELECT analysis_id FROM analysis_sources WHERE session_id=?) AND EXISTS (SELECT 1 FROM sessions WHERE id=? AND state_version=? AND status='withdrawn')").bind(s.id,s.id,next.state_version);
  const rows=next.status==='withdrawn'?await this.db.batch([update,clear]):[await update.run()];
  if(rows[0].meta.changes!==1){const fresh=await this.get(s.id);if(fresh){const receipt=fresh.session.receipts.find((r:any)=>r.id===command.request_id);if(receipt)return transition(fresh.session,g,command);}throw new ApiError(409,'STATE_CONFLICT');}
  return result;
 }
 async list(){const rows=await this.db.prepare("SELECT aggregate_json FROM sessions WHERE status!='withdrawn' AND expires_at>? ORDER BY id LIMIT 100").bind(new Date().toISOString()).all<{aggregate_json:string}>();return rows.results.map(r=>JSON.parse(r.aggregate_json));}
 async snapshot(sessions:any[],owner:string,options:any={}){
  if(!sessions.length||sessions.length>10||new Set(sessions.map(s=>s.id)).size!==sessions.length)throw new ApiError(422,'INVALID_SCOPE');
  const input=manifest(sessions),requestKey=options.request_key||crypto.randomUUID(),payload=options.payload||JSON.stringify(input);
  const prior=await this.db.prepare('SELECT id,payload_hash FROM analysis_runs WHERE request_key=?').bind(requestKey).first<{id:string;payload_hash:string}>();if(prior){if(prior.payload_hash!==payload)throw new ApiError(409,'IDEMPOTENCY_MISMATCH');return this.analysis(prior.id);}
  const single=options.resume_pending_single===true&&sessions.length===1&&options.scope==='single'&&options.status==='awaiting_provider',inputJson=JSON.stringify(input);
  // Observe the generation before looking up pending work. The INSERT checks it
  // atomically by requester + complete source manifest, not by client request ID.
  // Checking the generation also covers a rival that finishes before our INSERT;
  // a later, genuinely sequential rerun observes that completed generation.
  const latestSingle=()=>this.db.prepare("SELECT id FROM analysis_runs WHERE scope='single' AND requester_id=? AND input_manifest_json=? ORDER BY rowid DESC LIMIT 1").bind(owner,inputJson).first<{id:string}>();
  const observed=single?await latestSingle():null;
  if(single){const pending=await this.db.prepare("SELECT id FROM analysis_runs WHERE scope='single' AND requester_id=? AND status='awaiting_provider' AND result_json IS NULL AND input_manifest_json=? ORDER BY created_at ASC LIMIT 1").bind(owner,inputJson).first<any>();if(pending)return this.analysis(pending.id);}
  const id=crypto.randomUUID(),at=new Date().toISOString(),status=options.status||'awaiting_provider';
  try{const rows=await this.db.batch([this.db.prepare("INSERT INTO analysis_runs (id,scope,requester_id,input_manifest_json,status,result_json,created_at,request_key,payload_hash) SELECT ?,?,?,?,?,NULL,?,?,? WHERE NOT EXISTS (SELECT 1 FROM json_each(?) j LEFT JOIN sessions s ON s.id=json_extract(j.value,'$.session_id') WHERE s.id IS NULL OR s.content_revision!=json_extract(j.value,'$.content_revision') OR s.evidence_revision!=json_extract(j.value,'$.evidence_revision') OR s.status IN ('withdrawn','expired') OR s.expires_at<=?) AND (?=0 OR COALESCE((SELECT id FROM analysis_runs WHERE scope='single' AND requester_id=? AND input_manifest_json=? ORDER BY rowid DESC LIMIT 1),'')=?)").bind(id,options.scope||(sessions.length===1?'single':'cross'),owner,inputJson,status,at,requestKey,payload,inputJson,at,single?1:0,owner,inputJson,observed?.id||''),...sessions.map(s=>this.db.prepare('INSERT INTO analysis_sources (analysis_id,session_id,input_content_revision,input_evidence_revision) SELECT ?,?,?,? WHERE EXISTS (SELECT 1 FROM analysis_runs WHERE id=?)').bind(id,s.id,s.content_revision,s.evidence_revision,id))]);
   if(rows[0].meta.changes!==1){const winner=single?await latestSingle():null,run=winner?await this.analysis(winner.id):null;if(run?.status==='ready'&&!run.stale)return run;throw new ApiError(409,'STALE_ANALYSIS');}}
  catch{const other=await this.db.prepare('SELECT id,payload_hash FROM analysis_runs WHERE request_key=?').bind(requestKey).first<any>();if(other&&other.payload_hash===payload)return this.analysis(other.id);if(other)throw new ApiError(409,'IDEMPOTENCY_MISMATCH');throw new ApiError(409,'STALE_ANALYSIS');}return this.analysis(id);
 }
 async export(){return (await this.list()).map(exportSession);}
 async budget(){await this.db.prepare('INSERT OR IGNORE INTO service_control (id,revision,control_json) VALUES (?,0,?)').bind('global',JSON.stringify(initialBudget())).run();const r=await this.db.prepare('SELECT revision,control_json FROM service_control WHERE id=?').bind('global').first<{revision:number;control_json:string}>();if(!r)throw new ApiError(503,'CONTROL_UNAVAILABLE');return {...JSON.parse(r.control_json),revision:r.revision};}
 async updateBudget(apply:(c:any)=>any){for(let attempt=0;attempt<3;attempt++){const old=await this.budget(),next=apply(old);if(next.revision===old.revision)return next;const r=await this.db.prepare('UPDATE service_control SET revision=?,control_json=? WHERE id=? AND revision=?').bind(next.revision,JSON.stringify(next),'global',old.revision).run();if(r.meta.changes===1)return next;}throw new ApiError(409,'CONTROL_CONFLICT');}
 async reserve(request:any){return this.updateBudget(c=>reserveCall(c,request));}
 async settle(task:string,cost:number|null,options:{confirmed_finished?:boolean;cost_basis?:'actual'|'upper_bound'}={}){return this.updateBudget(c=>settleCall(c,task,cost,options));}
 async pauseLive(){return this.updateBudget(c=>{if(!c.live_enabled)return c;return {...c,live_enabled:false,revision:c.revision+1};});}
 async claimAttempt(id:string,task:{task_id:string;session_id:string;operation:string;content_revision:number},model:string){
  const r=await this.db.prepare("INSERT INTO provider_calls (id,task_id,operation,model,status,started_at) SELECT ?,?,?,?,'issued',? WHERE NOT EXISTS (SELECT 1 FROM provider_calls WHERE task_id=?) AND EXISTS (SELECT 1 FROM sessions WHERE id=? AND content_revision=? AND status!='withdrawn' AND (?='analysis' OR status='active') AND expires_at>? AND json_extract(aggregate_json,'$.consent.adult_confirmed')=1 AND json_extract(aggregate_json,'$.consent.research_agreed')=1 AND json_extract(aggregate_json,'$.consent.cloud_agreed')=1)").bind(id,task.task_id,task.operation,model,new Date().toISOString(),task.task_id,task.session_id,task.content_revision,task.operation,new Date().toISOString()).run();return r.meta.changes===1;
 }
 async claimCrossAttempt(id:string,task:{task_id:string},model:string,input:any[]){
  const r=await this.db.prepare("INSERT INTO provider_calls (id,task_id,operation,model,status,started_at) SELECT ?,?,'cross_analysis',?,'issued',? WHERE NOT EXISTS (SELECT 1 FROM provider_calls WHERE task_id=?) AND NOT EXISTS (SELECT 1 FROM json_each(?) j LEFT JOIN sessions s ON s.id=json_extract(j.value,'$.session_id') WHERE s.id IS NULL OR s.content_revision!=json_extract(j.value,'$.content_revision') OR s.evidence_revision!=json_extract(j.value,'$.evidence_revision') OR s.status IN ('withdrawn','expired') OR s.expires_at<=? OR COALESCE(json_extract(s.aggregate_json,'$.consent.adult_confirmed'),0)!=1 OR COALESCE(json_extract(s.aggregate_json,'$.consent.research_agreed'),0)!=1 OR COALESCE(json_extract(s.aggregate_json,'$.consent.cloud_agreed'),0)!=1)").bind(id,task.task_id,model,new Date().toISOString(),task.task_id,JSON.stringify(input),new Date().toISOString()).run();return r.meta.changes===1;
 }
 async finishAttempt(id:string,status:string,usage:unknown){await this.db.prepare('UPDATE provider_calls SET status=?,usage_json=?,ended_at=? WHERE id=?').bind(status,usage===null?null:JSON.stringify(usage),new Date().toISOString(),id).run();}
 async hasTranscriptionTask(task:string,s:any,questionId:string){const row=await this.db.prepare("SELECT usage_json FROM provider_calls WHERE task_id=? AND operation='stt' AND status='completed_cost_unknown'").bind(task).first<any>();if(!row?.usage_json)return false;const proof=JSON.parse(row.usage_json);return proof.session_id===s.id&&proof.question_id===questionId&&questionId===s.current&&proof.input_content_revision===s.content_revision&&proof.media_generation===(s.media_generation||0);}
 async safety(id:string,g:any,command:any){for(let attempt=0;attempt<3;attempt++){const row=await this.get(id);if(!row)throw new ApiError(404,'NOT_FOUND');const latest=row.session;if(command.type==='pause'&&latest.status==='ended')return {session:latest,replayed:true};try{return await this.mutate(latest,g,{...command,expected_version:latest.state_version});}catch(e){if((e as any).code!=='STATE_CONFLICT')throw e;}}throw new ApiError(409,'STATE_CONFLICT');}
 async study(){const row=await this.db.prepare('SELECT draft_json,draft_revision,current_published_guide_id,operations_json FROM studies WHERE id=?').bind('study-delta-force').first<any>();if(!row)throw new ApiError(503,'STUDY_UNAVAILABLE');return {draft:JSON.parse(row.draft_json),draft_revision:row.draft_revision,current_published_guide_id:row.current_published_guide_id,operations:JSON.parse(row.operations_json)};}
 async editStudy(input:any,expected:number,requestId:string,publishNow=false){
  const old=await this.study(),payload=JSON.stringify(publishNow?{publishNow:true}:{input,publishNow});const receipt=old.operations.find((x:any)=>x.id===requestId);if(receipt){if(receipt.payload!==payload)throw new ApiError(409,'IDEMPOTENCY_MISMATCH');return {draft:old.draft,draft_revision:old.draft_revision,guide:publishNow?await this.guide(receipt.guide_id):undefined,replayed:true};}if(old.draft_revision!==expected)throw new ApiError(409,'DRAFT_CONFLICT');
  // Publish validates fixed wording and budgets even when only saving a draft.
  const latest=await this.guide(),g=publish(input,(latest?.version||0)+1);const nextRevision=expected+1;
  const receipts=[...old.operations,{id:requestId,payload,guide_id:publishNow?g.id:null,result_revision:nextRevision}];
  const update=this.db.prepare('UPDATE studies SET draft_json=?,draft_revision=?,current_published_guide_id=?,operations_json=?,last_request_id=? WHERE id=? AND draft_revision=?').bind(JSON.stringify(input),nextRevision,publishNow?g.id:old.current_published_guide_id,JSON.stringify(receipts),requestId,'study-delta-force',expected);
  const insert=this.db.prepare('INSERT INTO guide_versions (id,study_id,version,guide_json,published_at) SELECT ?,?,?,?,? WHERE EXISTS (SELECT 1 FROM studies WHERE id=? AND draft_revision=? AND last_request_id=?)').bind(g.id,'study-delta-force',g.version,JSON.stringify(g),g.published_at,'study-delta-force',nextRevision,requestId);
  const rows=publishNow?await this.db.batch([update,insert]):[await update.run()];if(rows[0].meta.changes!==1)throw new ApiError(409,'DRAFT_CONFLICT');return {draft:input,draft_revision:nextRevision,...(publishNow?{guide:g}:{}),replayed:false};
 }
 async savedSingleAnalysis(sessionId:string){
  // Read legacy and new runs without a client-stored run ID or any provider work.
  // Keep the latest complete result visible even if a later attempt is pending.
  const row=await this.db.prepare("SELECT id FROM analysis_runs WHERE scope='single' AND requester_id=? AND json_array_length(input_manifest_json)=1 AND json_extract(input_manifest_json,'$[0].session_id')=? AND status NOT IN ('source_withdrawn','source_expired') ORDER BY CASE WHEN status='ready' THEN 0 ELSE 1 END, rowid DESC LIMIT 1").bind(sessionId,sessionId).first<{id:string}>();
  return row?this.analysis(row.id):null;
 }
 async analysis(id:string){const row=await this.db.prepare('SELECT * FROM analysis_runs WHERE id=?').bind(id).first<any>();if(!row)return null;const input=JSON.parse(row.input_manifest_json),result=row.result_json?JSON.parse(row.result_json):null;
  if(row.status==='source_withdrawn')return {id,status:row.status,scope:row.scope,requester_id:row.requester_id,input_manifest:[],findings:[],revision:row.revision,stale:true};
  const sessions:any[]=[];for(const item of input){const source=await this.get(item.session_id);if(source)sessions.push(source.session);}
  const unavailable=sessions.some(s=>s.status==='withdrawn'||s.status==='expired'||Date.parse(s.expires_at)<=Date.now())||sessions.length!==input.length;
  if(unavailable)return {id,status:'source_expired',scope:row.scope,requester_id:row.requester_id,input_manifest:[],findings:[],revision:row.revision,stale:true};
  const changed=stale({input_manifest:input},sessions);return {id,status:changed?'stale':row.status,scope:row.scope,requester_id:row.requester_id,input_manifest:input,findings:result?.findings||[],output_origin:result?.output_origin||null,denominators:result?.denominators||null,revision:row.revision,stale:changed};
 }
 async commitCandidates(id:string,output:any,origin='provider'){
  const run=await this.analysis(id);if(!run||run.stale)throw new ApiError(409,'STALE_ANALYSIS');const sessions:any[]=[];for(const item of run.input_manifest){const row=await this.get(item.session_id);if(!row)throw new ApiError(409,'STALE_ANALYSIS');sessions.push(row.session);}
  if(origin==='test_fixture'&&sessions.some(s=>s.origin!=='demo_fixture'))throw new ApiError(422,'TEST_ORIGIN_REQUIRED');if(!['test_fixture','provider'].includes(origin))throw new ApiError(422,'INVALID_ORIGIN');const validated=validateCandidates(output,sessions);
  const r=await this.db.prepare("UPDATE analysis_runs SET result_json=?,status='ready',revision=revision+1 WHERE id=? AND revision=? AND status IN ('awaiting_provider','blocked_live_disabled') AND NOT EXISTS (SELECT 1 FROM analysis_sources src JOIN sessions s ON s.id=src.session_id WHERE src.analysis_id=? AND (s.content_revision!=src.input_content_revision OR s.evidence_revision!=src.input_evidence_revision OR s.status IN ('withdrawn','expired') OR s.expires_at<=?))").bind(JSON.stringify({...validated,output_origin:origin,denominators:Object.fromEntries(sessionTopicIds(sessions).map(t=>[t,denominators(sessions,t)]))}),id,run.revision,id,new Date().toISOString()).run();if(r.meta.changes!==1)throw new ApiError(409,'STALE_ANALYSIS');return this.analysis(id);
 }
 async review(id:string,findingId:string,command:any,actor:string){
  const run=await this.analysis(id);if(!run||run.status==='source_withdrawn')throw new ApiError(404,'NOT_FOUND');if(run.stale)throw new ApiError(409,'STALE_ANALYSIS');if(run.status!=='ready')throw new ApiError(409,'ANALYSIS_NOT_READY');
  const row=await this.db.prepare('SELECT operations_json FROM analysis_runs WHERE id=?').bind(id).first<any>(),ops=JSON.parse(row.operations_json);const payload=JSON.stringify({...command,finding_id:findingId}),old=ops.find((o:any)=>o.id===command.request_id);if(old){if(old.payload!==payload)throw new ApiError(409,'IDEMPOTENCY_MISMATCH');return {...run,replayed:true};}if(run.revision!==command.expected_revision)throw new ApiError(409,'REVIEW_CONFLICT');
  const f=run.findings.find((f:any)=>f.id===findingId);if(!f)throw new ApiError(404,'FINDING_NOT_FOUND');if(!['approved','rejected','pending'].includes(command.review_status))throw new ApiError(422,'INVALID_REVIEW');if(command.claim!==undefined&&(typeof command.claim!=='string'||!command.claim.trim()||command.claim.length>1000))throw new ApiError(422,'INVALID_CLAIM');
  if(command.claim!==undefined)f.claim=command.claim.trim();f.review_status=command.review_status;f.review_history.push({status:f.review_status,claim:f.claim,actor,at:new Date().toISOString()});ops.push({id:command.request_id,payload});
  const r=await this.db.prepare("UPDATE analysis_runs SET result_json=?,operations_json=?,revision=revision+1 WHERE id=? AND revision=? AND status='ready' AND NOT EXISTS (SELECT 1 FROM analysis_sources src JOIN sessions s ON s.id=src.session_id WHERE src.analysis_id=? AND (s.content_revision!=src.input_content_revision OR s.evidence_revision!=src.input_evidence_revision OR s.status IN ('withdrawn','expired') OR s.expires_at<=?))").bind(JSON.stringify({findings:run.findings,output_origin:run.output_origin,denominators:run.denominators}),JSON.stringify(ops),id,run.revision,id,new Date().toISOString()).run();if(r.meta.changes!==1)throw new ApiError(409,'REVIEW_CONFLICT');return this.analysis(id);
 }
 async rate(key:string,maximum:number,window= Math.floor(Date.now()/60000)){
  const row=await this.db.prepare('INSERT INTO request_limits (key,window,count) VALUES (?,?,1) ON CONFLICT(key) DO UPDATE SET window=excluded.window,count=CASE WHEN request_limits.window=excluded.window THEN request_limits.count+1 ELSE 1 END WHERE request_limits.window!=excluded.window OR request_limits.count<? RETURNING count').bind(key,window,maximum).first<any>();if(!row)throw new ApiError(429,'REQUEST_LIMIT');
 }
 async creationQuota(key:string){return this.updateBudget(c=>reserveSessionEntry(c,key));}
 async cleanup(now=new Date().toISOString()){
  const rows=await this.db.prepare("SELECT aggregate_json FROM sessions WHERE expires_at<=? AND status NOT IN ('withdrawn','expired') LIMIT 20").bind(now).all<any>();let cleaned=0;
  for(const row of rows.results){const s=JSON.parse(row.aggregate_json);const tombstone={id:s.id,guide_id:s.guide_id,origin:s.origin,status:'expired',expires_at:s.expires_at,state_version:s.state_version+1,content_revision:s.content_revision+1,evidence_revision:s.evidence_revision+1,questions:[],answers:[],exposures:[],receipts:[],task:null,current:null};
   const result=await this.db.batch([this.db.prepare("UPDATE sessions SET aggregate_json=?,status='expired',state_version=?,content_revision=?,evidence_revision=? WHERE id=? AND state_version=? AND expires_at<=?").bind(JSON.stringify(tombstone),tombstone.state_version,tombstone.content_revision,tombstone.evidence_revision,s.id,s.state_version,now),this.db.prepare("UPDATE analysis_runs SET result_json=NULL,input_manifest_json='[]',operations_json='[]',status='source_withdrawn',revision=revision+1 WHERE id IN (SELECT analysis_id FROM analysis_sources WHERE session_id=?) AND EXISTS (SELECT 1 FROM sessions WHERE id=? AND status='expired')").bind(s.id,s.id)]);if(result[0].meta.changes===1)cleaned++;
  }await this.db.prepare('DELETE FROM request_limits WHERE window<? AND key NOT LIKE ?').bind(Math.floor(Date.now()/60000)-10,'creation:%').run();return {cleaned,remaining_possible:rows.results.length===20};
 }
}
