import {sqliteTable,text,integer,uniqueIndex,index} from 'drizzle-orm/sqlite-core';
export const studies=sqliteTable('studies',{id:text('id').primaryKey(),owner:text('owner_site_user_id').notNull(),title:text('title').notNull(),draft:text('draft_json').notNull(),revision:integer('draft_revision').notNull().default(0),guide:text('current_published_guide_id'),created:text('created_at').notNull(),operations:text('operations_json').notNull().default('[]'),lastRequest:text('last_request_id')});
export const guides=sqliteTable('guide_versions',{id:text('id').primaryKey(),study:text('study_id').notNull().references(()=>studies.id),version:integer('version').notNull(),guide:text('guide_json').notNull(),published:text('published_at').notNull()},t=>[uniqueIndex('guide_study_version').on(t.study,t.version)]);
export const sessions=sqliteTable('sessions',{id:text('id').primaryKey(),study:text('study_id').notNull(),guide:text('guide_id').notNull(),origin:text('origin').notNull(),token:text('token_hash').notNull(),request:text('create_request_id').notNull().unique(),requestHash:text('create_payload_hash').notNull(),version:integer('state_version').notNull(),content:integer('content_revision').notNull(),evidence:integer('evidence_revision').notNull(),status:text('status').notNull(),expires:text('expires_at').notNull(),aggregate:text('aggregate_json').notNull()},t=>[index('sessions_guide_origin').on(t.guide,t.origin),index('sessions_expiry').on(t.expires)]);
export const analyses=sqliteTable('analysis_runs',{id:text('id').primaryKey(),scope:text('scope').notNull(),owner:text('requester_id').notNull(),manifest:text('input_manifest_json').notNull(),status:text('status').notNull(),result:text('result_json'),created:text('created_at').notNull(),revision:integer('revision').notNull().default(0),request:text('request_key').unique(),payload:text('payload_hash'),operations:text('operations_json').notNull().default('[]')});
export const analysisSources=sqliteTable('analysis_sources',{analysis:text('analysis_id').notNull().references(()=>analyses.id),session:text('session_id').notNull().references(()=>sessions.id),content:integer('input_content_revision').notNull().default(0),evidence:integer('input_evidence_revision').notNull().default(0)},t=>[uniqueIndex('analysis_source_pair').on(t.analysis,t.session),index('source_session').on(t.session)]);
export const rates=sqliteTable('request_limits',{key:text('key').primaryKey(),window:integer('window').notNull(),count:integer('count').notNull()},t=>[index('rate_window').on(t.window)]);
export const service=sqliteTable('service_control',{id:text('id').primaryKey(),revision:integer('revision').notNull().default(0),control:text('control_json').notNull()});
export const calls=sqliteTable('provider_calls',{id:text('id').primaryKey(),task:text('task_id').notNull(),operation:text('operation').notNull(),model:text('model').notNull(),status:text('status').notNull(),usage:text('usage_json'),started:text('started_at').notNull(),ended:text('ended_at')});
