// User-supplied brief snapshot: 2026-10-04. This is a configuration, never completed research.
export const legacyDetonationCaseKey='detonation-first-session-v1';
export const legacyDetonationDraft=Object.freeze({
 title:'Delta Force Detonation Beta: First-Session Experience and What Players Do Next',
 goal:'Understand what prompted first Detonation play, defining moments, and the next actual game choice. Independent hackathon research, not an official Delta Force study. First session means the first continuous period of actual play, ending on leaving the mode; earlier tests count. Next occasion means the next game play after leaving, not another match in the same session. No later opportunity is not churn; intention is not behavior. Preserve dates, platform/region and uncertainty when supplied; do not generalize accounts before the September 30 update to the current build. Identify strengths, issues to inspect and hypotheses, not prevalence, causality, balance judgments or validated solutions. Defaults and no customization are valid; no relevant experience, not remembered and refusal remain distinct. Researcher manually verifies eligibility/background before inviting; unconfirmed details stay unknown. All seven fixed questions precede at most two neutral probes.',
 game:'Delta Force — Detonation (Beta)',game_build:'Brief snapshot 2026-10-04; participant build UNKNOWN',
 target_players:'Manual eligibility review: actual first Detonation match on/after 2026-09-27, first session ended (early exit eligible), first session in the prior seven calendar days. For this 2026-10-04 case use Sep27–Oct4 inclusive. Prior Operations/Warfare OR actual bomb-defusal play elsewhere in prior three months. Both backgrounds may apply; missing is unknown. Videos/lobby only, unfinished session or earlier tests are outside scope. The app does not determine eligibility.',
 questions:[
  {text:'What prompted you to try Detonation for the first time?',allow_followups:false,followup_limit:0},
  {text:'Before you started, what were you hoping to get out of the mode?',allow_followups:false,followup_limit:0},
  {text:'Walk me through how you got your equipment ready for your first round.',allow_followups:true,followup_limit:1},
  {text:'Tell me about the moment that stands out most from that first session.',allow_followups:false,followup_limit:0},
  {text:'What role, if any, did your experience with other games or modes play in that session?',allow_followups:false,followup_limit:0},
  {text:'The next time you played a game after that session, what did you choose to play?',allow_followups:true,followup_limit:1},
  {text:'If you could share one thing about that experience with the development team, what would it be?',allow_followups:false,followup_limit:0}
 ]
});
export const detonationModeratorPolicy='This saved case is first-session qualitative research, not a retention estimate. Never assume promotion, rewards, friends, weapon customization, mastery, wins/losses or disappointment explain a choice. A default loadout is valid. Probe equipment only for a missing experience detail, once; a concrete process/rationale/reaction is sufficient. For next play, interpret the entire answer: "I did not return, but played Operations" is an actual choice. If no later play occasion occurred, advance without asking why they quit or predicting return. Probe a later choice only for its missing reason, once. Never spend unused probes just to exhaust budget. Preserve possible misunderstanding and uncertain date/platform/build; do not correct or silently rewrite the account. Accept missing memory, irrelevant experience, refusal and immediate end. Eligibility is manually reviewed, not automatically established by this interview.';
// A fresh guide identity is required. Never rewrite a saved v1 guide or its evidence.
export const detonationCaseKey='detonation-first-session-v2';
export const detonationDraft=Object.freeze({
 ...legacyDetonationDraft,
 goal:'Understand what prompted first Detonation play, the defining first-session experience, and the next actual game choice. Independent research, not an official study. First session ends when leaving the mode; earlier tests count. Next occasion means playing any game after leaving, not another match in that session. No later opportunity is not churn; intention is not behavior. Preserve dates, platform/region/build and uncertainty; do not generalize pre-update accounts. Seek strengths, issues and hypotheses, not prevalence, causality, balance judgments or validated solutions. Eligibility/background are manually reviewed; missing information stays unknown. Ask four fixed main questions, with an immediate neutral probe only when needed: T2 at most one, T3 at most one, two total. Accept sufficient answers, missing memory and refusal without repeated probing.',
 questions:[
  {...legacyDetonationDraft.questions[0]},
  {...legacyDetonationDraft.questions[3],allow_followups:true,followup_limit:1},
  {text:'Since that first session ended, what, if anything, have you played next?',allow_followups:true,followup_limit:1},
  {...legacyDetonationDraft.questions[6]}
 ]
});
export const isDetonationCase=key=>[legacyDetonationCaseKey,detonationCaseKey].includes(key);
export const detonationImmediateModeratorPolicy='This is first-session qualitative research, not a retention estimate. Ask about the experience the participant actually describes. For a vague judgment such as "matchmaking was bad; everyone was unskilled", a neutral probe can request a recent specific moment; never presume a matchmaking mechanism, imbalance, teammate ability or cause. Do not force a probe for every answer. Concrete event, action and relevant reaction/reason are sufficient; do not repeat details already supplied. A participant may describe a positive, negative or mixed moment. For next play, interpret the whole answer: not returning to Detonation but playing Operations is an actual choice. If no subsequent game play occurred, accept that and advance; never ask why they quit or treat future intention as behavior. If the next choice is clear but its reason is missing, one neutral probe is allowed. Never spend unused quota merely to exhaust it. Preserve uncertain date/platform/build and accept correction, missing memory, no relevant experience, refusal, pause and immediate end. Eligibility/background remain manually reviewed, never automatically established.';
export const matchesDetonationDraft=d=>JSON.stringify(d)===JSON.stringify(detonationDraft);
export function detonationExample(){
 const themes=legacyDetonationDraft.questions.map((q,i)=>({id:'T'+(i+1),fixed_id:'F'+(i+1),name:['First-session trigger','Expectations','Equipment preparation','Defining moment','Prior experience','Next actual choice','Feedback to preserve'][i],text:q.text,budget:q.followup_limit}));
 const guide={kind:'custom',research_case:legacyDetonationCaseKey,id:'detonation-fictional-guide-v1',version:1,...legacyDetonationDraft,themes,language:'en'};
 const rows=[
  ['A friend invited me after we played Operations. I entered my first Detonation match on October 3 and left the mode after two matches.','I hoped to learn how the bomb mode worked with that group.','Gearing up was a hassle. I could not tell which saved setup was active, so I asked my friend before the round.','I held an angle while my friend planted. I felt useful even though we lost that round.','Operations helped me find my friends, but it did not tell me how to choose a setup here. Other bomb-mode experience is unknown.','I just finished that first session. I have not played any game since.','Keep the teamwork moments. I would like to understand which setup is active before starting.'],
  ['I chose to try the mode on October 2 after seeing it in the menu. My first session has ended. Prior bomb-defusal play in another game was within three months.','Nothing in particular; I wanted to see what it was like.','I used the default equipment. It worked for me; I wanted to learn the basic rules first. I did not customize anything.','A teammate dropped equipment for me after a mistake. That moment stands out.','Other bomb games helped me recognize when to wait. I am not claiming mastery or equivalence between games.','The next time I played, I chose Operations because my usual group was already there. I have not returned to Detonation.','Preserve teammates being able to help. I do not have an improvement suggestion.']
 ];
 const sessions=rows.map((texts,i)=>({id:'detonation-fictional-'+(i+1),guide_id:guide.id,guide_snapshot:guide,topic_ids:themes.map(t=>t.id),research_case:legacyDetonationCaseKey,origin:'demo_fixture',status:'ended',mode:'text',mode_group:'text_only',content_revision:14,evidence_revision:14,created_at:'2026-10-04T06:00:00Z',expires_at:'2026-10-11T06:00:00Z',eligibility_status:'fictional example only; no actual screening conducted',questions:themes.map((t,j)=>({id:`detonation-${i+1}-q${j+1}`,theme_id:t.id,fixed_question_id:t.fixed_id,kind:'fixed',actual_text:t.text,sequence:j+1})),answers:texts.map((text,j)=>({id:`detonation-${i+1}-a${j+1}`,question_id:`detonation-${i+1}-q${j+1}`,revision:1,final_text:text,response_status:'valid',input_mode:'text'}))}));
 const span=(i,j)=>{const s=sessions[i],a=s.answers[j];return {session_id:s.id,question_id:a.question_id,answer_id:a.id,answer_revision:1,input_content_revision:s.content_revision,start_utf16:0,end_utf16:a.final_text.length,exact_quote:a.final_text};};
 return {origin:'demo_fixture',status:'complete',guide,source_sessions:sessions,note:'Manually authored simulated examples: two fictional accounts, not real interviews or model output. Eligibility is unconfirmed as research; dates/build/platform cannot be generalized. No prevalence, retention or causal conclusion.',findings:[
  {id:'detonation-example-equipment',theme_ids:['T3'],claim:'In fictional account A, identifying the active setup was unclear; account B found the defaults sufficient.',supporting_spans:[span(0,2)],counter_spans:[span(1,2)],unknowns:['These are two invented cases, not a denominator for real players.','Account B is counterevidence to a universal equipment-confusion claim.','Interface, platform and actual build require verification; no solution is validated.'],review_status:'pending'},
  {id:'detonation-example-next-choice',theme_ids:['T6'],claim:'The fictional accounts distinguish no later play occasion from an actual choice of another mode.',supporting_spans:[span(0,5),span(1,5)],counter_spans:[],unknowns:['A has no subsequent play occasion; this is not churn.','B reports an actual choice with a stated social reason; intention is not substituted for behavior.','Neither account estimates retention or establishes what caused a population to leave.'],review_status:'pending'}
 ]};
}

// New user-approved case; v1/v2 first-session exports above remain immutable.
export const gameplayCaseKey='detonation-gameplay-feedback-v3';
export const gameplayDraft=Object.freeze({
 title:'Delta Force Detonation: Maps, Operators and Equipment Economy',
 goal:'Understand player feedback on map design, perceived operator balance, and how weapon customization and the purchasing economy affect choices in Detonation. Ground impressions in concrete experiences when available. Identify strengths, issues to investigate and hypotheses, not objective balance verdicts, prevalence, causality or validated solutions. Do not assume particular mechanics, prices, abilities or outcomes. Preserve uncertain dates, platform, region and build. This is independent research, not an official study. Ask three main questions with optional immediate clarification: at most one probe per topic and two probes across the interview. Accept sufficient detail, no relevant experience, missing memory and refusal without repeated probing.',
 game:'Delta Force - Detonation',game_build:'Participant build UNKNOWN',
 target_players:'Players who have played Detonation and can describe their experience of maps, operators or equipment choices. No first-session or return requirement. Missing background, date, platform and build details remain unknown. Fictional practice answers are separate from human research.',
 questions:[
  {text:'How do you feel about the map design in Detonation?',allow_followups:true,followup_limit:1},
  {text:'How balanced do the operators feel in Detonation?',allow_followups:true,followup_limit:1},
  {text:'How does the weapon customization and purchasing economy affect your choices in Detonation?',allow_followups:true,followup_limit:1}
 ]
});
export const gameplayModeratorPolicy='Explore map design, perceived operator balance, and weapon customization/purchasing economy only as described by the participant. For a general impression, one neutral probe may ask for a specific experience or missing reason; do not require a negative or positive answer. Never invent map features, operator abilities, weapon systems, prices or purchase rules. Perceived balance is a report, not proof of objective imbalance. Do not force both customization and purchasing examples when only one is relevant. Advance when detail is sufficient or the participant lacks experience, cannot remember or declines. At most one probe per topic and two total. Do not ask about first-session triggers, returning or future play unless directly relevant volunteered context.';
export function gameplayExample(){
 const themes=gameplayDraft.questions.map((q,i)=>({id:'T'+(i+1),fixed_id:'F'+(i+1),name:['Map design','Perceived operator balance','Customization and purchasing economy'][i],text:q.text,budget:1}));
 const guide={kind:'custom',research_case:gameplayCaseKey,routing_policy:'immediate-probes-v1',id:'detonation-gameplay-fictional-guide-v3',version:3,...gameplayDraft,themes,language:'en',session_probe_limit:2};
 const rows=[
  ['In this invented example I hesitated at a junction because I could not tell which route reached my teammate.','In this invented example one operator felt hard to respond to, but I cannot recall enough detail to explain why.','In this invented example I kept my current weapon setup because I was unsure what the alternative would cost.'],
  ['In this invented example I recognized the route to my teammate and felt comfortable choosing it.','In this invented example I did not notice a clear difference between operators; I have limited experience.','In this invented example I chose familiar equipment and did not consider customizing it.']
 ];
 const sessions=rows.map((texts,i)=>({id:'gameplay-fictional-'+(i+1),guide_id:guide.id,guide_snapshot:guide,topic_ids:themes.map(t=>t.id),research_case:gameplayCaseKey,origin:'demo_fixture',status:'ended',mode:'text',mode_group:'text_only',content_revision:6,evidence_revision:6,created_at:'2026-10-04T10:00:00Z',expires_at:'2026-10-11T10:00:00Z',questions:themes.map((t,j)=>({id:'gameplay-'+i+'-q'+j,guide_id:guide.id,theme_id:t.id,fixed_question_id:t.fixed_id,kind:'fixed',actual_text:t.text,sequence:j+1})),answers:texts.map((text,j)=>({id:'gameplay-'+i+'-a'+j,question_id:'gameplay-'+i+'-q'+j,revision:1,final_text:text,response_status:'valid',input_mode:'text'}))}));
 const span=(i,j)=>{const s=sessions[i],a=s.answers[j];return {session_id:s.id,question_id:a.question_id,answer_id:a.id,answer_revision:1,input_content_revision:s.content_revision,start_utf16:0,end_utf16:a.final_text.length,exact_quote:a.final_text};};
 return {origin:'demo_fixture',status:'complete',guide,source_sessions:sessions,note:'Hand-authored fictional examples, not real interviews or model output. No mechanics, balance or design solution is validated.',findings:[
  {id:'gameplay-map-example',theme_ids:['T1'],claim:'The fictional accounts describe different levels of confidence in choosing a route.',supporting_spans:[span(0,0)],counter_spans:[span(1,0)],unknowns:['Invented examples only; map, platform and context are unverified.'],review_status:'pending'},
  {id:'gameplay-operator-example',theme_ids:['T2'],claim:'The fictional operator impressions lack enough detail for a balance conclusion.',supporting_spans:[span(0,1),span(1,1)],counter_spans:[],unknowns:['No objective imbalance or ability mechanism is established.'],review_status:'pending'},
  {id:'gameplay-economy-example',theme_ids:['T3'],claim:'The fictional accounts describe uncertainty about cost and a preference for familiar equipment.',supporting_spans:[span(0,2),span(1,2)],counter_spans:[],unknowns:['No price, purchase rule or effect on outcomes is established.'],review_status:'pending'}
 ]};
}
